import{describe,expect,it,vi}from'vitest';import{ConfirmationActionRegistry,getSystemTestData,normalizeCardAction}from'../src/foundry/actions';
describe('SR5 message compatibility',()=>{it('reads the current TestData flag',()=>{const message={getFlag:vi.fn((_scope:string,key:string)=>key==='TestData'?{data:{type:'RangedAttackTest'}}:undefined)};expect(getSystemTestData(message)?.data.type).toBe('RangedAttackTest');expect(message.getFlag).toHaveBeenCalledWith('shadowrun5e','TestData')});it('falls back to the legacy test key',()=>{const message={getFlag:vi.fn((_scope:string,key:string)=>key==='test'?{data:{type:'SkillTest'}}:undefined)};expect(getSystemTestData(message)?.data.type).toBe('SkillTest')})});
describe('card action compatibility',()=>{it('maps legacy action names to generic actions',()=>{expect(normalizeCardAction('defend')).toEqual({action:'run-stage',stageId:'defense'});expect(normalizeCardAction('resist')).toEqual({action:'run-stage',stageId:'soak'});expect(normalizeCardAction('apply-damage')).toEqual({action:'confirm',confirmId:'damageApplied',confirmKind:'damage'});expect(normalizeCardAction('run-stage')).toEqual({action:'run-stage'})})});
describe('confirmation action registry',()=>{it('registers handlers once',()=>{const registry=new ConfirmationActionRegistry(),handler=vi.fn();const unregister=registry.register('damage',handler);expect(registry.get('damage')).toBe(handler);expect(()=>registry.register('damage',handler)).toThrow('already registered');unregister()})});
describe('apply effects confirmation',()=>{
 const setup=(branch:any,docs:Record<string,any>)=>{(globalThis as any).ui={notifications:{warn:vi.fn(),error:vi.fn()}};(globalThis as any).game={user:{id:'gm',isGM:true},i18n:{localize:(k:string)=>k,format:(k:string)=>k,has:()=>false},settings:{get:()=>'publicroll'}};(globalThis as any).fromUuid=vi.fn(async(uuid:string)=>docs[uuid]);const stored:any={schemaVersion:2,flowId:'item-use',id:'t1',revision:3,authorId:'gm',createdAt:1,updatedAt:1,origin:{id:'o',kind:'ItemUseAction',modifiers:[],createdAt:1},branches:{[branch.id]:branch},events:[],complete:true};const message:any={uuid:'Message.1',isAuthor:true,getFlag:()=>stored,update:vi.fn(async()=>{})};return{message,stored}};
 it('warns without pending effects and refuses double application',async()=>{const{confirmationActions}=await import('../src/foundry/actions');const handler=confirmationActions.get('effect');const branch:any={id:'a',kind:'target',actorUuid:'Actor.a',name:'A',stageId:'done',rolls:{},stageData:{},derived:{},confirmations:{}};const{message}=setup(branch,{});await handler(message,branch);expect((globalThis as any).ui.notifications.warn).toHaveBeenCalledWith('SDF.Error.NoPendingEffects');branch.derived.pendingEffects=1;branch.confirmations.effectsApplied={at:1,by:'gm',payload:{}};await handler(message,branch);expect((globalThis as any).ui.notifications.warn).toHaveBeenCalledWith('SDF.Error.EffectsAlreadyApplied')});
 it('creates stored effect copies with appliedByTest and records the confirmation',async()=>{const{confirmationActions}=await import('../src/foundry/actions');const handler=confirmationActions.get('effect');const createEmbeddedDocuments=vi.fn(async()=>[]);const branch:any={id:'a',kind:'target',actorUuid:'Actor.a',name:'A',stageId:'done',rolls:{},stageData:{effects:{itemUuid:'Item.x',source:'deferred',effects:[{name:'Blind',changes:[],system:{applyTo:'targeted_actor'}}]}},derived:{pendingEffects:1},confirmations:{}};const{message}=setup(branch,{'Actor.a':{testUserPermission:()=>true,createEmbeddedDocuments}});await handler(message,branch);expect(createEmbeddedDocuments).toHaveBeenCalledWith('ActiveEffect',[expect.objectContaining({name:'Blind',disabled:false,'system.appliedByTest':true,'flags.sr5-dice-flow.appliedFrom':'Item.x'})]);expect(message.update).toHaveBeenCalled();const saved=message.update.mock.calls[0][0]['flags.sr5-dice-flow.transaction'];expect(saved.branches.a.confirmations.effectsApplied.payload).toMatchObject({itemUuid:'Item.x',names:['Blind'],count:1})});
 it('re-collects oversized payloads live and enables disabled self effects',async()=>{const{confirmationActions}=await import('../src/foundry/actions');const handler=confirmationActions.get('effect');const createEmbeddedDocuments=vi.fn(async()=>[]);const branch:any={id:'s',kind:'self',actorUuid:'Actor.s',name:'S',stageId:'done',rolls:{},stageData:{effects:{itemUuid:'Item.drug',source:'item',oversized:true,effects:[{name:'Rush',changes:[]}]}},derived:{selfPendingEffects:1},confirmations:{}};const item={effects:[{disabled:true,system:{applyTo:'actor'},toObject:()=>({name:'Rush',disabled:true,changes:[],system:{applyTo:'actor'}})}]};const{message}=setup(branch,{'Actor.s':{testUserPermission:()=>true,createEmbeddedDocuments},'Item.drug':item});await handler(message,branch);expect(createEmbeddedDocuments).toHaveBeenCalledWith('ActiveEffect',[expect.objectContaining({name:'Rush',disabled:false})]);const created=(createEmbeddedDocuments.mock.calls[0]as any[])[1][0];expect(created['system.appliedByTest']).toBeUndefined();const saved=message.update.mock.calls[0][0]['flags.sr5-dice-flow.transaction'];expect(saved.branches.s.confirmations.selfEffectsApplied).toBeDefined()});
});
