import{describe,expect,it}from'vitest';import{FlowRegistry}from'../src/core/flows/registry';import type{FlowSpec}from'../src/core/flows/spec';import{routeFollowup}from'../src/core/flows/router';import{createReducerRegistry}from'../src/core/reducers';import{addTarget,createTransaction}from'../src/core/transaction';import type{RollRecord}from'../src/types';
const record=(id:string,kind='DefenseTest',hits=1):RollRecord=>({id,kind,hits,modifiers:[],createdAt:1});
const spec:FlowSpec={id:'capture-test',match:()=>true,branches:'targets+self',initialStage:branch=>branch.kind==='self'?'drain':'defense',stages:[{id:'defense',branch:'perTarget',testClasses:['DefenseTest'],trigger:'button',reduce:'opposedHits',next:{always:'done'}},{id:'drain',branch:'self',testClasses:['DrainTest'],trigger:'systemFollowup',reduce:'merge',next:{always:'done'}}]};
const setup=()=>{const flows=new FlowRegistry(),reducers=createReducerRegistry();flows.register(spec);let tx=createTransaction({kind:'Attack',hits:4,defenseTest:'DefenseTest',actorUuid:'Actor.caster',modifiers:[]},'u');tx.flowId=spec.id;tx=addTarget(tx,0,'u',{id:'target',actorUuid:'Actor.target',name:'Target'});tx.branches.self={id:'self',kind:'self',actorUuid:'Actor.caster',name:'Caster',stageId:'drain',rolls:{},stageData:{},derived:{},confirmations:{}};return{flows,reducers,tx}};
describe('capture router',()=>{
 it('routes target stages by marker and invokes their reducer',()=>{const{flows,reducers,tx}=setup();const result=routeFollowup(tx,{testClass:'DefenseTest',actorUuid:'Actor.other',targetId:'target',data:{}},record('r1'), 'u',flows,reducers);expect(result.status).toBe('captured');expect(result.transaction.branches.target).toMatchObject({stageId:'done',rolls:{defense:{id:'r1'}},derived:{netHits:3}})});
 it('routes self followups by the origin actor',()=>{const{flows,reducers,tx}=setup();const result=routeFollowup(tx,{testClass:'DrainTest',actorUuid:'Actor.caster',data:{derived:{drainValue:2}}},record('r2','DrainTest'),'u',flows,reducers);expect(result.status).toBe('captured');expect(result.transaction.branches.self).toMatchObject({stageId:'done',derived:{drainValue:2}})});
 it('keeps unmatched followups as one idempotent info event',()=>{const{flows,reducers,tx}=setup();const result=routeFollowup(tx,{testClass:'FadeTest',actorUuid:'Actor.caster'},record('r3','FadeTest'),'u',flows,reducers);expect(result.status).toBe('unmatched');expect(result.transaction.events.at(-1)).toMatchObject({type:'followup.unmatched',payload:{rollId:'r3',reason:'stage-unmatched'}});const repeated=routeFollowup(result.transaction,{testClass:'FadeTest',actorUuid:'Actor.caster'},record('r3','FadeTest'),'u',flows,reducers);expect(repeated.status).toBe('duplicate');expect(repeated.transaction.events).toHaveLength(result.transaction.events.length)});
 it('is idempotent per roll id',()=>{const{flows,reducers,tx}=setup();const first=routeFollowup(tx,{testClass:'DefenseTest',targetId:'target'},record('same'),'u',flows,reducers);const second=routeFollowup(first.transaction,{testClass:'DefenseTest',targetId:'target'},record('same'),'u',flows,reducers);expect(second.status).toBe('duplicate');expect(second.transaction).toBe(first.transaction)});
 it('survives a self-branch key mangled by Foundry expandObject',()=>{const{flows,reducers,tx}=setup();const mangled={...tx,branches:{...tx.branches,'self-Actor':{caster:{id:'self-Actor.caster',kind:'self',actorUuid:'Actor.caster',name:'Caster',stageId:'drain',rolls:{},stageData:{},derived:{},confirmations:{}}}}};delete(mangled.branches as any).self;let result:ReturnType<typeof routeFollowup>|undefined;expect(()=>{result=routeFollowup(mangled as any,{testClass:'DefenseTest',actorUuid:'Actor.other',targetId:'target',data:{}},record('rm'),'u',flows,reducers)}).not.toThrow();expect(result!.status).toBe('captured')});
 it('reports unavailable flows and missing marker targets without throwing',()=>{const{flows,reducers,tx}=setup();expect(routeFollowup({...tx,flowId:'unknown'},{testClass:'DefenseTest'},record('x'),'u',flows,reducers)).toMatchObject({status:'unmatched',reason:'flow-unavailable'});expect(routeFollowup(tx,{testClass:'DefenseTest',targetId:'gone'},record('y'),'u',flows,reducers)).toMatchObject({status:'unmatched',reason:'target-missing'})});
});
