import{beforeEach,describe,expect,it}from'vitest';import{registerCoreFlowSpecs}from'../src/core/flows/specs';import{addTarget,createTransaction}from'../src/core/transaction';import{renderCard}from'../src/foundry/card';import{registerGeneralPresentation}from'../src/foundry/general';import type{Branch,RollRecord}from'../src/types';
beforeEach(()=>{(globalThis as any).game={user:{id:'u',isGM:true},i18n:{localize:(key:string)=>key,format:(key:string,data:any)=>`${key} ${Object.values(data??{}).join(' ')}`,has:()=>false}};registerCoreFlowSpecs();registerGeneralPresentation()});
const tx=(flowId:string,origin:Partial<RollRecord>)=>{const value=createTransaction({kind:'SkillTest',pool:10,modifiers:[],...origin}as RollRecord,'u');value.flowId=flowId;return value};
const withTarget=(flowId:string,origin:Partial<RollRecord>,branch:Partial<Branch>)=>{let value=tx(flowId,origin);value=addTarget(value,value.revision,'u',{id:'t',actorUuid:'Actor.t',name:'Ziel'});Object.assign(value.branches.t!,branch);return value};
const railState=(html:string,stage:string)=>html.match(new RegExp(`data-rail-stage="${stage}"[^>]*data-state="([a-z]+)"`))?.[1];
describe('semantic verdict tones',()=>{
 it('paints a passed threshold test as a general success, never as an attack impact',()=>{const html=renderCard(tx('generic-simple',{hits:4,threshold:3}));expect(html).toContain('sdf-verdict--success');expect(html).not.toContain('sdf-verdict--impact')});
 it('paints a missed threshold test as a general failure',()=>{const html=renderCard(tx('generic-simple',{hits:1,threshold:3}));expect(html).toContain('sdf-verdict--failure');expect(html).not.toContain('sdf-verdict--deflected')});
 it('keeps the impact tone for an attack that lands on the target',()=>{const html=renderCard(withTarget('combat-attack',{hits:4,defenseTest:'PhysicalDefenseTest'},{stageId:'soak',rolls:{defense:{id:'d',kind:'PhysicalDefenseTest',hits:1,modifiers:[],createdAt:1}},derived:{netHits:3,modifiedDamage:6,damageType:'physical'}}));expect(html).toContain('sdf-verdict--impact');expect(html).not.toContain('sdf-verdict--success')});
 it('paints a deflected attack with its own tone rather than the general success tone',()=>{const html=renderCard(withTarget('combat-attack',{hits:4,defenseTest:'PhysicalDefenseTest'},{stageId:'done',rolls:{defense:{id:'d',kind:'PhysicalDefenseTest',hits:5,modifiers:[],createdAt:1}},derived:{netHits:0,finalDamage:0}}));expect(html).toContain('sdf-verdict--deflected');expect(html).not.toContain('sdf-verdict--success')});
 it('paints a completed extended test as a success rather than an impact',()=>{const value=tx('extended',{hits:9});value.branches.s={id:'s',kind:'self',actorUuid:'Actor.s',name:'Läufer',stageId:'done',rolls:{},stageData:{origin:{extended:{hits:9,threshold:8,complete:true}}},derived:{},confirmations:{}};const html=renderCard(value);expect(html).toContain('sdf-verdict--success');expect(html).not.toContain('sdf-verdict--impact')});
});
describe('stage rail',()=>{
 it('lists the branch stage sequence and marks the current and next step',()=>{const html=renderCard(withTarget('combat-attack',{hits:4,defenseTest:'PhysicalDefenseTest',resistanceTest:'PhysicalResistTest'},{stageId:'defense'}));expect(html).toContain('sdf-rail');expect(railState(html,'defense')).toBe('current');expect(railState(html,'soak')).toBe('next');expect(railState(html,'done')).toBe('pending')});
 it('exposes the current step to assistive technology',()=>{const html=renderCard(withTarget('combat-attack',{hits:4,defenseTest:'PhysicalDefenseTest'},{stageId:'defense'}));expect(html).toMatch(/<ol[^>]*class="sdf-rail"[^>]*aria-label="SDF\.Rail\.Label"/);expect(html.match(/aria-current="step"/g)?.length).toBe(1)});
 it('marks a rolled step as done and an unrolled bypassed step as skipped',()=>{const html=renderCard(withTarget('combat-attack',{hits:4,defenseTest:'PhysicalDefenseTest'},{stageId:'done',rolls:{defense:{id:'d',kind:'PhysicalDefenseTest',hits:5,modifiers:[],createdAt:1}},derived:{netHits:0,finalDamage:0}}));expect(railState(html,'defense')).toBe('done');expect(railState(html,'soak')).toBe('skipped');expect(railState(html,'done')).toBe('current')});
 it('holds the rail on a step whose mutation still needs confirmation',()=>{const html=renderCard(withTarget('combat-attack',{hits:4,defenseTest:'PhysicalDefenseTest'},{stageId:'done',rolls:{defense:{id:'d',kind:'PhysicalDefenseTest',hits:1,modifiers:[],createdAt:1},soak:{id:'s',kind:'PhysicalResistTest',hits:2,modifiers:[],createdAt:2}},derived:{netHits:3,finalDamage:4,damageType:'physical'}}));expect(railState(html,'soak')).toBe('current');expect(railState(html,'done')).toBe('next')});
 it('names each step with its own short label instead of the pending-status phrase',()=>{const html=renderCard(withTarget('combat-attack',{hits:4,defenseTest:'PhysicalDefenseTest'},{stageId:'defense'}));expect(html).toContain('SDF.Step.defense');expect(html).toContain('SDF.Step.soak')});
 it('omits the rail for a branch without a real sequence',()=>{const value=tx('generic-simple',{hits:4,threshold:3});expect(renderCard(value)).not.toContain('sdf-rail')});
});
describe('action priority tiers',()=>{
 it('renders a pending flow roll as the primary flow action',()=>{const html=renderCard(withTarget('combat-attack',{hits:4,defenseTest:'PhysicalDefenseTest'},{stageId:'defense'}));expect(html).toMatch(/data-sdf-action="defend"[^>]*class="[^"]*sdf-btn--flow/)});
 it('separates an actor-mutating confirmation from ordinary flow actions',()=>{const html=renderCard(withTarget('combat-attack',{hits:4,defenseTest:'PhysicalDefenseTest'},{stageId:'done',rolls:{defense:{id:'d',kind:'PhysicalDefenseTest',hits:1,modifiers:[],createdAt:1}},derived:{netHits:3,finalDamage:4,damageType:'physical'}}));expect(html).toMatch(/data-sdf-action="confirm"[^>]*class="[^"]*sdf-btn--commit/);expect(html).not.toMatch(/data-sdf-action="confirm"[^>]*class="[^"]*sdf-btn--flow/)});
 it('renders the GM correction as a quiet tertiary action',()=>{const html=renderCard(withTarget('combat-attack',{hits:4,defenseTest:'PhysicalDefenseTest'},{stageId:'defense'}),{isGM:true});expect(html).toMatch(/data-sdf-action="correct"[^>]*class="[^"]*sdf-btn--gm/)});
 it('groups the mutating confirmation in its own commit zone',()=>{const html=renderCard(withTarget('combat-attack',{hits:4,defenseTest:'PhysicalDefenseTest'},{stageId:'done',rolls:{defense:{id:'d',kind:'PhysicalDefenseTest',hits:1,modifiers:[],createdAt:1}},derived:{netHits:3,finalDamage:4,damageType:'physical'}}));expect(html).toContain('sdf-commit-zone')});
});
describe('heal branch presentation',()=>{
 const healTx=()=>{let value=tx('heal',{kind:'SkillTest',hits:4,threshold:2});value=addTarget(value,value.revision,'u',{id:'p',actorUuid:'Actor.p',name:'Patient'});return value};
 it('keeps the track select inside the branch section that the confirm action reads',()=>{const html=renderCard(healTx());expect(html).toMatch(/class="[^"]*sdf-target[^"]*"[\s\S]*data-sdf-heal-track[\s\S]*data-sdf-action="confirm"/);expect(html).toContain('value="physical"');expect(html).toContain('value="stun"')});
 it('treats applying the heal as a commit action',()=>{const html=renderCard(healTx());expect(html).toMatch(/data-confirm-kind="heal"[^>]*>|data-sdf-action="confirm"[^>]*class="[^"]*sdf-btn--commit/);expect(html).toContain('sdf-btn--commit')});
 it('shows the pending treatment step as the current rail step',()=>{const html=renderCard(healTx());expect(railState(html,'apply')).toBe('current')});
 it('marks the treatment step done once the heal was confirmed',()=>{const value=healTx();value.branches.p!.confirmations.healApplied={at:1,by:'u',payload:{amount:2,track:'stun'}};const html=renderCard(value);expect(railState(html,'apply')).toBe('done');expect(railState(html,'done')).toBe('current')});
});
