import{beforeAll,describe,expect,it}from'vitest';import{registerCoreFlowSpecs}from'../src/core/flows/specs';import{createTransaction}from'../src/core/transaction';import{registerCombatPresentation}from'../src/foundry/combat';import{captureCombatBefore,combatOriginExtractor}from'../src/foundry/extract';import{renderCard}from'../src/foundry/card';
beforeAll(()=>{(globalThis as any).game={i18n:{localize:(key:string)=>key,format:(key:string,data:any)=>`${key} ${data.revision}`,has:()=>false}};registerCoreFlowSpecs();registerCombatPresentation()});
describe('combat origin extraction',()=>{
 it('extracts fire mode, real before/after ammo and recoil, ranges, reach and grouped modifiers',()=>{let recoil=2;const test:any={actor:{recoil:()=>recoil},item:{system:{ammo:{current:{value:30,max:40}}},totalRecoilCompensation:4}};captureCombatBefore(test);test.item.system.ammo.current.value=27;recoil=5;const result:any=combatOriginExtractor({testClass:'RangedAttackTest',test,data:{fireMode:{label:'SR5.FireMode.BF',value:3,defense:-2,action:'simple'},range:-1,reach:2,targetRanges:[{tokenUuid:'Token.a',distance:18,range:{label:'SR5.Range.medium',modifier:-1}}],pool:{changes:[{name:'SR5.Range',value:-1},{name:'SR5.Recoil',value:-2},{name:'SR5.Wounds',value:-1},{name:'SR5.Environmental',value:-3}]}}});expect(result.combat).toMatchObject({fireMode:{rounds:3,defense:-2},ammo:{before:30,after:27,max:40},recoil:{before:2,after:5,compensation:4},range:-1,reach:2,targetRanges:[{tokenUuid:'Token.a',distance:18,modifier:-1}]});expect(Object.keys(result.combat.poolGroups)).toEqual(['range','recoil','wounds','environment'])});
 const multiTargetTx=(flowId:string,targets:number,pool=12)=>{const tx=createTransaction({kind:'RangedAttackTest',hits:4,pool,modifiers:[]},'u');tx.flowId=flowId;const origin={combat:{fireMode:{label:'BF',rounds:3,defense:-2}}};for(let i=0;i<targets;i++)tx.branches[`t${i}`]={id:`t${i}`,kind:'target',actorUuid:`Actor.${i}`,name:`Target ${i}`,stageId:'defense',rolls:{},stageData:{origin},derived:{},confirmations:{}};tx.branches.self={id:'self',kind:'self',actorUuid:'Actor.attacker',name:'Attacker',stageId:'done',rolls:{},stageData:{origin},derived:{},confirmations:{}};return tx};
 it('extracts a called shot from the declared tag or the surviving pool modifier',()=>{const viaTag:any=combatOriginExtractor({testClass:'RangedAttackTest',data:{calledShot:{key:'vitals',label:'SDF.CalledShot.vitals',mod:4}}});expect(viaTag.combat.calledShot).toMatchObject({key:'vitals',label:'SDF.CalledShot.vitals',mod:4});const viaPool:any=combatOriginExtractor({testClass:'RangedAttackTest',data:{pool:{changes:[{name:'SDF.CalledShotModifier',value:-4,enabled:true}]}}});expect(viaPool.combat.calledShot).toMatchObject({mod:4});const none:any=combatOriginExtractor({testClass:'RangedAttackTest',data:{}});expect(none.combat.calledShot).toBeUndefined()});
 it('renders the called-shot section and the announced badge plus toggle',()=>{const origin={combat:{calledShot:{key:'vitals',label:'SDF.CalledShot.vitals',mod:4}}};const tx=createTransaction({kind:'RangedAttackTest',hits:3,modifiers:[]},'u');tx.flowId='combat-attack';tx.calledShotAnnounced=true;tx.branches.a={id:'a',kind:'target',actorUuid:'Actor.a',name:'Target',stageId:'defense',rolls:{},stageData:{origin},derived:{},confirmations:{}};const html=renderCard(tx,{isGM:true});expect(html).toContain('SDF.CalledShot.Type');expect(html).toContain('sdf-called-shot-badge');expect(html).toContain('data-sdf-action="announce-called-shot"')});
 it('shows the multi-attack pool-split advisory only for combat attacks on more than one target',()=>{const many=renderCard(multiTargetTx('combat-attack',3,12));expect(many).toContain('sdf-combat-advisory');expect(many).toContain('SDF.Combat.MultiAttack');expect(many).toContain('SDF.Combat.PoolSplitHint');const one=renderCard(multiTargetTx('combat-attack',1,12));expect(one).not.toContain('sdf-combat-advisory');const supp=renderCard(multiTargetTx('suppression',3,12));expect(supp).not.toContain('sdf-combat-advisory')});
 it('renders the extracted combat section and one deferred-ammo confirmation',()=>{const tx=createTransaction({kind:'RangedAttackTest',hits:3,modifiers:[]},'u');tx.flowId='combat-attack';const origin={combat:{fireMode:{label:'BF',rounds:3,defense:-2},ammo:{before:30,after:30,plannedAfter:27,max:40,deferred:true,rounds:3,itemUuid:'Item.weapon'},recoil:{before:2,after:5,compensation:4},targetRanges:[{tokenUuid:'Token.a',distance:18,label:'Medium',modifier:-1}],poolGroups:{range:[{name:'Range',value:-1}]}}};tx.branches.a={id:'a',kind:'target',actorUuid:'Actor.a',tokenUuid:'Token.a',name:'Target',stageId:'defense',rolls:{},stageData:{origin},derived:{},confirmations:{}};tx.branches.self={id:'self',kind:'self',actorUuid:'Actor.attacker',name:'Attacker',stageId:'done',rolls:{},stageData:{origin},derived:{ammoPending:3},confirmations:{}};const html=renderCard(tx);expect(html).toContain('SDF.Combat.FireMode');expect(html).toContain('30 → 27 / 40');expect(html).toContain('SDF.Combat.AmmoPending');expect(html).toContain('data-confirm-kind="ammo"');expect(html.match(/data-confirm-kind="ammo"/g)).toHaveLength(1);expect(html).toContain('2 → 5');expect(html).toContain('Target · 18 m · Medium (-1)');expect(html).toContain('SDF.Combat.Group.range')});
});
