import{beforeEach,describe,expect,it,vi}from'vitest';import{effectsInternals}from'../src/foundry/effects';import{addTarget,createTransaction}from'../src/core/transaction';
const{deferUnopposed,deferOpposed,collectEffects}=effectsInternals;
const raw={name:'Blind',img:'i.png',changes:[],system:{applyTo:'targeted_actor',changes:[{key:'k',mode:2,value:'2'}]}};
function makeMessage(){let tx=createTransaction({kind:'ThrownAttackTest',hits:4,modifiers:[]},'author');tx=addTarget(tx,0,'author',{id:'a',actorUuid:'Actor.a',name:'A'});const message:any={uuid:'Message.1',isAuthor:true,stored:tx,getFlag:(_m:string,_k:string)=>message.stored,update:vi.fn(async(data:any)=>{message.stored=data['flags.sr5-dice-flow.transaction']})};return message}
beforeEach(()=>{(globalThis as any).game={user:{id:'author',isGM:false},i18n:{localize:(k:string)=>k,format:(k:string)=>k,has:()=>false},settings:{get:()=>'publicroll'},messages:{get:()=>undefined}}});
describe('deferred effect application',()=>{
 it('collects only non-empty effect arrays',()=>{expect(collectEffects({effects:{_collectTargetActorEffectsData:()=>[raw]}})).toEqual([raw]);expect(collectEffects({effects:{_collectTargetActorEffectsData:()=>[]}})).toBeUndefined();expect(collectEffects({}))?.toBeUndefined()});
 it('defers unopposed targeted effects onto matching target branches',async()=>{const message=makeMessage();(globalThis as any).fromUuid=vi.fn(async()=>message);const test={opposing:false,opposed:false,targets:[{actor:{uuid:'Actor.a'}}],effects:{_collectTargetActorEffectsData:()=>[raw]},data:{messageUuid:'Message.1'},item:{uuid:'Item.x',name:'Flashbang'}};expect(await deferUnopposed(test)).toBe(true);const branch=message.stored.branches.a;expect(branch.derived.pendingEffects).toBe(1);expect(branch.stageData.effects).toMatchObject({itemUuid:'Item.x',source:'deferred',effects:[{name:'Blind'}]})});
 it('falls back to the system when branch coverage is partial or the transaction is missing',async()=>{const message=makeMessage();(globalThis as any).fromUuid=vi.fn(async()=>message);const test:any={opposing:false,opposed:false,targets:[{actor:{uuid:'Actor.a'}},{actor:{uuid:'Actor.unknown'}}],effects:{_collectTargetActorEffectsData:()=>[raw]},data:{messageUuid:'Message.1'},item:{}};expect(await deferUnopposed(test)).toBe(false);expect(message.update).not.toHaveBeenCalled();(globalThis as any).fromUuid=vi.fn(async()=>undefined);test.targets=[{actor:{uuid:'Actor.a'}}];expect(await deferUnopposed(test)).toBe(false);expect(await deferUnopposed({...test,opposed:true})).toBe(false)});
 it('routes opposed failures via the flow marker and refuses double deferral',async()=>{const message=makeMessage();(globalThis as any).game.messages={get:(id:string)=>id==='m1'?message:undefined};const test={against:{},actor:{uuid:'Actor.a'},effects:{_collectTargetActorEffectsData:()=>[raw]},data:{previousMessageId:'m1',sr5DiceFlow:{messageId:'m1',targetId:'a'}},item:{uuid:'Item.x',name:'Flashbang'}};expect(await deferOpposed(test)).toBe(true);expect(message.stored.branches.a.derived.pendingEffects).toBe(1);expect(await deferOpposed(test)).toBe(false)});
 it('falls back to actor matching without a marker and refuses unknown defenders',async()=>{const message=makeMessage();(globalThis as any).game.messages={get:()=>message};const test:any={against:{},actor:{uuid:'Actor.a'},effects:{_collectTargetActorEffectsData:()=>[raw]},data:{previousMessageId:'m1'},item:{uuid:'Item.x'}};expect(await deferOpposed(test)).toBe(true);const stranger={...test,actor:{uuid:'Actor.zz'},data:{previousMessageId:'m1'}};const fresh=makeMessage();(globalThis as any).game.messages={get:()=>fresh};expect(await deferOpposed(stranger)).toBe(false)});
});
describe('pendingEffects mutation security',()=>{
 it('skips the revision check and gates on author, GM or branch owner',async()=>{const{validateMutation}=await import('../src/foundry/security');const tx:any={id:'t1',revision:5,authorId:'author'};const request=(action:string,userId:string,actorUuid?:string)=>({transactionId:'t1',expectedRevision:0,action,payload:{actorUuid},requestId:'r',userId});(globalThis as any).fromUuid=async(uuid:string)=>uuid==='Actor.owned'?{testUserPermission:()=>true}:{testUserPermission:()=>false};await expect(validateMutation(tx,request('pendingEffects','author')as any,{id:'author',isGM:false})).resolves.toBe(true);await expect(validateMutation(tx,request('pendingEffects','player','Actor.owned')as any,{id:'player',isGM:false})).resolves.toBe(true);await expect(validateMutation(tx,request('pendingEffects','player','Actor.other')as any,{id:'player',isGM:false})).rejects.toThrow('Author, GM or branch owner');await expect(validateMutation(tx,request('confirm','player','Actor.owned')as any,{id:'player',isGM:false})).rejects.toThrow('Revision conflict')});
});
