import{describe,expect,it}from'vitest';import{GLOBAL_CONFIRMATIONS,confirmationAvailable,isGlobalConfirmation}from'../src/core/flows/confirmation';import{buildPendingEffects,pendingEffectNames,sanitizeEffect}from'../src/core/effects';import{addTarget,createTransaction,setPendingEffects}from'../src/core/transaction';
const baseTx=()=>{let tx=createTransaction({kind:'ThrownAttackTest',hits:4,modifiers:[]},'author');tx=addTarget(tx,0,'author',{id:'a',actorUuid:'Actor.a',name:'A'});tx=addTarget(tx,1,'author',{id:'b',actorUuid:'Actor.b',name:'B'});return tx};
describe('pending effects mutation',()=>{
 it('records effects per branch and derives the confirmation counter by branch kind',()=>{let tx=baseTx();tx.branches.self1={id:'self1',kind:'self',actorUuid:'Actor.s',name:'S',stageId:'done',rolls:{},stageData:{},derived:{},confirmations:{}};const payload={itemUuid:'Item.x',itemName:'Flashbang',source:'deferred',effects:[{name:'Blind',changes:[]}]};tx=setPendingEffects(tx,tx.revision,'author',[{branchId:'a',effects:payload,count:1},{branchId:'self1',effects:payload,count:2}]);expect(tx.branches.a!.stageData.effects).toEqual(payload);expect(tx.branches.a!.derived.pendingEffects).toBe(1);expect(tx.branches.self1!.derived.selfPendingEffects).toBe(2);expect(tx.branches.b!.stageData.effects).toBeUndefined();expect(tx.events.at(-1)).toMatchObject({type:'effects.pending',payload:{branchIds:['a','self1'],count:3}})});
 it('refuses unknown branches, double sets and stale revisions',()=>{const tx=baseTx();expect(()=>setPendingEffects(tx,tx.revision,'author',[{branchId:'zz',effects:{},count:1}])).toThrow('Unknown branch');const set=setPendingEffects(tx,tx.revision,'author',[{branchId:'a',effects:{},count:1}]);expect(()=>setPendingEffects(set,set.revision,'author',[{branchId:'a',effects:{},count:1}])).toThrow('already recorded');expect(()=>setPendingEffects(set,0,'author',[{branchId:'b',effects:{},count:1}])).toThrow()});
 it('exposes the global effect confirmations exactly while pending and unconfirmed',()=>{const tx=setPendingEffects(baseTx(),2,'author',[{branchId:'a',effects:{},count:2}]);const branch=tx.branches.a!,confirm=GLOBAL_CONFIRMATIONS[0]!;expect(confirm).toMatchObject({id:'effectsApplied',kind:'effect'});expect(confirmationAvailable(confirm,branch)).toBe(true);expect(confirmationAvailable(GLOBAL_CONFIRMATIONS[1]!,branch)).toBe(false);branch.confirmations.effectsApplied={at:1,by:'author',payload:{}};expect(confirmationAvailable(confirm,branch)).toBe(false);expect(isGlobalConfirmation('effectsApplied','effect')).toBe(true);expect(isGlobalConfirmation('effectsApplied','damage')).toBe(false);expect(isGlobalConfirmation('damageApplied','effect')).toBe(false)});
});
describe('effect sanitizer',()=>{
 it('keeps the mechanical payload and drops bookkeeping fields',()=>{const raw={_id:'x',_stats:{},sort:5,origin:'Actor.y',description:'<p>huge</p>',name:'Blitzkompensation',img:'icons/x.png',disabled:false,changes:[{key:'system.attributes.reaction',mode:2,value:'-2',priority:10,extra:'drop'}],duration:{rounds:10},statuses:['blind'],system:{applyTo:'targeted_actor',changes:[{key:'k',mode:2,value:'3'}]}};const clean=sanitizeEffect(raw);expect(clean).toEqual({name:'Blitzkompensation',img:'icons/x.png',changes:[{key:'system.attributes.reaction',mode:2,value:'-2',priority:10}],disabled:undefined,duration:{rounds:10},statuses:['blind'],system:raw.system});expect((clean as any)._id).toBeUndefined()});
 it('falls back to name-only snapshots beyond the size budget',()=>{const raw=[{name:'Big',img:'i.png',system:{applyTo:'targeted_actor',blob:'x'.repeat(4096)}}];const ok=buildPendingEffects(raw,{itemUuid:'Item.x',source:'deferred'});expect(ok.oversized).toBeUndefined();expect(ok.effects[0]!.system).toBeDefined();const small=buildPendingEffects(raw,{itemUuid:'Item.x',source:'deferred'},512);expect(small.oversized).toBe(true);expect(small.effects).toEqual([{name:'Big',img:'i.png',changes:[]}]);expect(pendingEffectNames(small)).toEqual(['Big'])});
});
