import{describe,expect,it,vi}from'vitest';import{advance}from'../src/core/flows/engine';import{ExtractorRegistry,FlowRegistry}from'../src/core/flows/registry';import type{FlowSpec}from'../src/core/flows/spec';import{createReducerRegistry,ReducerRegistry}from'../src/core/reducers';import{addTarget,createTransaction}from'../src/core/transaction';import type{Branch,RollRecord}from'../src/types';
const roll=(id:string,hits=1):RollRecord=>({id,kind:id,hits,modifiers:[],createdAt:1});
const spec:FlowSpec={id:'test-flow',match:origin=>origin.testClass==='Attack',branches:'targets',initialStage:()=> 'defense',stages:[{id:'defense',branch:'perTarget',testClasses:['DefenseTest'],trigger:'button',reduce:'opposedHits',next:{onSuccess:'soak',onFailure:'done'}},{id:'soak',branch:'perTarget',testClasses:['SoakTest'],trigger:'button',reduce:'soakDamage',next:{always:'done'}}]};
const setup=()=>{const registry=new FlowRegistry();registry.register(spec);let tx=createTransaction({kind:'Attack',hits:4,defenseTest:'DefenseTest',modifiers:[]},'u');tx.flowId=spec.id;tx=addTarget(tx,0,'u',{id:'a',actorUuid:'Actor.a',name:'A'});return{registry,tx}};
describe('flow engine',()=>{
 it('advances a branch, merges reduced data and records the roll without mutating input',()=>{const{registry,tx}=setup();const out=advance(tx,'a','defense',roll('defense',1),{outcome:'success',derived:{netHits:3},stageData:{source:'system'}},registry);expect(tx.branches.a!.stageId).toBe('defense');expect(out.branches.a).toMatchObject({stageId:'soak',rolls:{defense:{id:'defense'}},stageData:{defense:{source:'system'}},derived:{netHits:3}});expect(out.revision).toBe(tx.revision+1);expect(out.events.at(-1)).toMatchObject({type:'stage.advanced',payload:{branchId:'a',nextStageId:'soak'}})});
 it('uses outcome transitions and completes only after every branch is done',()=>{const{registry,tx:one}=setup();let tx=addTarget(one,1,'u',{id:'b',actorUuid:'Actor.b',name:'B'});tx=advance(tx,'a','defense',roll('a-defense',4),{outcome:'failure'},registry);expect(tx.complete).toBe(false);tx=advance(tx,'b','defense',roll('b-defense',4),{outcome:'failure'},registry);expect(tx.complete).toBe(true)});
 it('rejects unknown branches, stale stages, repeats and wrong branch kinds',()=>{const{registry,tx}=setup();expect(()=>advance(tx,'missing','defense',roll('x'),{outcome:'success'},registry)).toThrow('Unknown branch');expect(()=>advance(tx,'a','soak',roll('x'),{outcome:'success'},registry)).toThrow('not soak');const advanced=advance(tx,'a','defense',roll('x'),{outcome:'success'},registry);expect(()=>advance(advanced,'a','defense',roll('y'),{outcome:'success'},registry)).toThrow('not defense');const selfTx=structuredClone(tx);selfTx.branches.a!.kind='self';expect(()=>advance(selfTx,'a','defense',roll('x'),{outcome:'success'},registry)).toThrow('does not accept branch kind self')});
 it('requires a transition matching the reducer outcome',()=>{const{registry,tx}=setup();expect(()=>advance(tx,'a','defense',roll('x'),{},registry)).toThrow('No transition')});
});
describe('registries and capabilities',()=>{
 it('matches enabled specs in registration order',()=>{const registry=new FlowRegistry(),fallback={...spec,id:'fallback',match:()=>true};registry.register(spec);registry.register(fallback);expect(registry.match({testClass:'Attack',data:{}})?.id).toBe('test-flow');expect(registry.match({testClass:'Other',data:{}})?.id).toBe('fallback')});
 it('disables only specs with missing test classes, reducers or extractors',()=>{const registry=new FlowRegistry(),warn=vi.fn();registry.register({...spec,originExtract:['missing']});registry.register({...spec,id:'healthy',originExtract:['present'],stages:[{...spec.stages[0]!,testClasses:['Present'],reduce:'merge'}]});const result=registry.checkCapabilities({Present:{}},id=>id==='merge',id=>id==='present',warn);expect(result.map(x=>({id:x.spec.id,enabled:x.enabled}))).toEqual([{id:'test-flow',enabled:false},{id:'healthy',enabled:true}]);expect(result[0]?.missingExtractors).toEqual(['missing']);expect(registry.match({testClass:'Attack',data:{}})?.id).toBe('healthy');expect(()=>registry.get('test-flow')).toThrow('disabled');expect(warn).toHaveBeenCalledOnce()});
 it('registers named reducers and rejects duplicates and unknown ids',()=>{const registry=new ReducerRegistry(),fn=vi.fn(()=>({}));const unregister=registry.register('custom',fn);expect(registry.get('custom')).toBe(fn);expect(()=>registry.register('custom',fn)).toThrow('already registered');unregister();expect(()=>registry.get('custom')).toThrow('Unknown reducer');expect(createReducerRegistry().ids()).toEqual(['merge','opposedHits','soakDamage'])});
 it('registers named origin extractors',()=>{const registry=new ExtractorRegistry(),extract=vi.fn(()=>({ammo:3}));const unregister=registry.register('ammo',extract);expect(registry.get('ammo')).toBe(extract);expect(registry.ids()).toEqual(['ammo']);expect(()=>registry.register('ammo',extract)).toThrow('already registered');unregister();expect(registry.has('ammo')).toBe(false)});
 it('built-in reducers remain pure',()=>{const registry=createReducerRegistry(),branch:Branch={id:'a',kind:'target',actorUuid:'Actor.a',name:'A',stageId:'soak',rolls:{},stageData:{},derived:{modifiedDamage:8},confirmations:{}};expect(registry.get('opposedHits')({transactionId:'tx',branch,origin:roll('attack',5),roll:roll('defense',2),stage:spec.stages[0]!})).toMatchObject({outcome:'success',derived:{netHits:3}});expect(registry.get('soakDamage')({transactionId:'tx',branch,origin:roll('attack'),roll:roll('soak',3),stage:spec.stages[1]!})).toMatchObject({outcome:'success',derived:{soakHits:3,finalDamage:5}});expect(branch.derived).toEqual({modifiedDamage:8})});
});
