import{beforeAll,describe,expect,it}from'vitest';import{FlowRegistry}from'../src/core/flows/registry';import{confirmationAvailable}from'../src/core/flows/confirmation';import{extended,heal}from'../src/core/flows/specs/general';import{genericOpposed,genericSimple}from'../src/core/flows/specs/generic';import{extendedProgressExtractor}from'../src/foundry/general';import{registerCoreFlowSpecs}from'../src/core/flows/specs';import{addTarget,createTransaction}from'../src/core/transaction';import{renderCard}from'../src/foundry/card';
const registry=()=>{const flows=new FlowRegistry();flows.register(heal);flows.register(extended);flows.register(genericOpposed);flows.register(genericSimple);return flows};
beforeAll(()=>{(globalThis as any).game={i18n:{localize:(key:string)=>key,format:(key:string,data:any)=>`${key} ${data.revision??''}`,has:()=>false}};registerCoreFlowSpecs()});
describe('general M4 flows',()=>{
 it('matches heal actions and extended tests ahead of the simple fallback',()=>{const flows=registry();expect(flows.match({testClass:'SkillTest',data:{action:{skill:'first_aid'}}})?.id).toBe('heal');expect(flows.match({testClass:'SkillTest',data:{extended:true}})?.id).toBe('extended');expect(flows.match({testClass:'SkillTest',data:{action:{skill:'perception'}}})?.id).toBe('generic-simple')});
 it('exposes a heal confirmation on each patient branch',()=>{let tx=createTransaction({kind:'SkillTest',hits:3,modifiers:[]},'medic');tx.flowId='heal';tx=addTarget(tx,0,'medic',{id:'p',actorUuid:'Actor.p',name:'Patient'});const healConfirm=heal.stages[0]!.confirm!.find(c=>c.kind==='heal')!;expect(confirmationAvailable(healConfirm,tx.branches.p!)).toBe(true);tx.branches.p!.confirmations.healApplied={at:1,by:'medic',payload:{amount:3}};expect(confirmationAvailable(healConfirm,tx.branches.p!)).toBe(false)});
 it('extracts cumulative extended progress and completion',()=>{const running:any=extendedProgressExtractor({testClass:'SkillTest',data:{extended:true,values:{extendedHits:{value:3}},threshold:{value:8}}});expect(running.extended).toMatchObject({hits:3,threshold:8,complete:false});const done:any=extendedProgressExtractor({testClass:'SkillTest',data:{extended:true,values:{extendedHits:{value:8}},threshold:{value:8}}});expect(done.extended.complete).toBe(true)});
 it('renders a threshold verdict and edge line on a simple card',()=>{const success=createTransaction({kind:'SkillTest',title:'Perception',pool:10,hits:4,threshold:3,modifiers:[]},'u');success.flowId='generic-simple';expect(renderCard(success)).toContain('SDF.Succeeded');const failure=createTransaction({kind:'SkillTest',pool:10,hits:1,threshold:3,modifiers:[]},'u');failure.flowId='generic-simple';expect(renderCard(failure)).toContain('SDF.Failed');const edged=createTransaction({kind:'SkillTest',pool:10,hits:5,edge:{pushTheLimit:true},modifiers:[]},'u');edged.flowId='generic-simple';const html=renderCard(edged);expect(html).toContain('sdf-edge');expect(html).toContain('SDF.Edge.PushTheLimit')});
 it('does not show a verdict when the flow has target branches',()=>{let tx=createTransaction({kind:'RangedAttackTest',pool:10,hits:4,threshold:3,defenseTest:'PhysicalDefenseTest',modifiers:[]},'u');tx.flowId='combat-attack';tx=addTarget(tx,0,'u',{id:'a',actorUuid:'Actor.a',name:'A'});expect(renderCard(tx)).not.toContain('SDF.Succeeded')});
});
