import{describe,expect,it}from'vitest';import{FlowRegistry}from'../src/core/flows/registry';import{effectList,hasTargetedItemEffects,isSelfEffect,isTargetedEffect,itemUse}from'../src/core/flows/specs/items';import{heal,extended}from'../src/core/flows/specs/general';import{genericOpposed,genericSimple}from'../src/core/flows/specs/generic';
const targeted={name:'Blind',system:{applyTo:'targeted_actor'}};const disabledActor={name:'Rush',disabled:true,system:{applyTo:'actor'}};
const registry=()=>{const flows=new FlowRegistry();flows.register(heal);flows.register(extended);flows.register(itemUse);flows.register(genericOpposed);flows.register(genericSimple);return flows};
describe('item effect helpers',()=>{
 it('collects own and nested item effects from iterables',()=>{const item={effects:new Set([targeted]),items:new Set([{effects:[disabledActor]},{}])};expect(effectList(item)).toEqual([targeted,disabledActor]);expect(effectList(undefined)).toEqual([]);expect(hasTargetedItemEffects(item)).toBe(true);expect(hasTargetedItemEffects({effects:[disabledActor]})).toBe(false);expect(hasTargetedItemEffects({effects:[{...targeted,disabled:true}]})).toBe(false)});
 it('classifies self-applicable effects as targeted or disabled actor effects',()=>{expect(isSelfEffect(targeted)).toBe(true);expect(isSelfEffect(disabledActor)).toBe(true);expect(isSelfEffect({system:{applyTo:'actor'},disabled:false})).toBe(false);expect(isTargetedEffect({system:{applyTo:'test_all'}})).toBe(false)});
});
describe('item-use FlowSpec',()=>{
 it('matches un-opposed tests whose item carries targeted effects',()=>{const flows=registry();expect(flows.match({testClass:'SuccessTest',data:{},test:{item:{effects:[targeted]}}})?.id).toBe('item-use');expect(flows.match({testClass:'SuccessTest',data:{},test:{item:{effects:[disabledActor]}}})?.id).toBe('generic-simple');expect(flows.match({testClass:'SuccessTest',data:{},test:{}})?.id).toBe('generic-simple')});
 it('cedes to heal, extended and opposed flows',()=>{const flows=registry();expect(flows.match({testClass:'SuccessTest',data:{action:{skill:'first_aid'}},test:{item:{effects:[targeted]}}})?.id).toBe('heal');expect(flows.match({testClass:'SuccessTest',data:{extended:true},test:{item:{effects:[targeted]}}})?.id).toBe('extended');expect(flows.match({testClass:'SuccessTest',data:{opposed:{test:'PhysicalDefenseTest'}},test:{item:{effects:[targeted]}}})?.id).toBe('generic-opposed')});
 it('starts every branch at done with targets+self',()=>{expect(itemUse.branches).toBe('targets+self');expect(itemUse.initialStage({}as any)).toBe('done');expect(itemUse.stages).toEqual([]);expect(itemUse.originExtract).toEqual(['itemUse']);expect(itemUse.cardSections).toEqual(['itemUse'])});
});
