import{describe,expect,it}from'vitest';import{FlowRegistry}from'../src/core/flows/registry';import{routeFollowup}from'../src/core/flows/router';import{confirmationAvailable}from'../src/core/flows/confirmation';import{combatSoakReducer}from'../src/core/flows/specs/combat';import{matrix,complexForm,spriteCompiling,overwatchCheck,matrixDefenseReducer,fadeResistReducer}from'../src/core/flows/specs/matrix';import{summonServicesReducer}from'../src/core/flows/specs/magic';import{genericOpposed,genericSimple}from'../src/core/flows/specs/generic';import{createReducerRegistry}from'../src/core/reducers';import{addTarget,createTransaction}from'../src/core/transaction';import type{Branch,RollRecord}from'../src/types';
const roll=(id:string,kind:string,hits:number):RollRecord=>({id,kind,hits,modifiers:[],createdAt:1});
const registry=()=>{const flows=new FlowRegistry(),reducers=createReducerRegistry();reducers.register('combatSoak',combatSoakReducer);reducers.register('matrixDefense',matrixDefenseReducer);reducers.register('fadeResist',fadeResistReducer);reducers.register('summonServices',summonServicesReducer);flows.register(matrix);flows.register(complexForm);flows.register(spriteCompiling);flows.register(overwatchCheck);flows.register(genericOpposed);flows.register(genericSimple);return{flows,reducers}};
describe('matrix flows',()=>{
 it('routes matrix actions, complex forms, sprites and overwatch to their specs',()=>{const{flows}=registry();expect(flows.match({testClass:'BruteForceTest',data:{opposed:{test:'OpposedBruteForceTest'}}})?.id).toBe('matrix');expect(flows.match({testClass:'MatrixTest',data:{opposed:{test:'MatrixDefenseTest'}}})?.id).toBe('matrix');expect(flows.match({testClass:'ComplexFormTest',data:{}})?.id).toBe('complex-form');expect(flows.match({testClass:'CompileSpriteTest',data:{}})?.id).toBe('sprite-compiling');expect(flows.match({testClass:'CheckOverwatchScoreTest',data:{}})?.id).toBe('overwatch-check')});
 it('runs a data spike through matrix defense and resist',()=>{const{flows,reducers}=registry();let tx=createTransaction({kind:'MatrixTest',hits:5,defenseTest:'MatrixDefenseTest',resistanceTest:'MatrixResistTest',modifiers:[]},'decker');tx.flowId='matrix';tx=addTarget(tx,0,'decker',{id:'a',actorUuid:'Actor.a',name:'Host'});tx.branches.a!.stageId=matrix.initialStage(tx.branches.a!,tx.origin);expect(tx.branches.a!.stageId).toBe('defense');const defense=routeFollowup(tx,{testClass:'MatrixDefenseTest',targetId:'a',data:{modifiedDamage:{value:9,type:{value:'matrix'}}}},roll('d','MatrixDefenseTest',1),'a',flows,reducers);expect(defense).toMatchObject({status:'captured',transaction:{branches:{a:{stageId:'soak',derived:{netHits:4,modifiedDamage:9,damageType:'matrix'}}}}});const soak=routeFollowup((defense as any).transaction,{testClass:'MatrixResistTest',targetId:'a',data:{modifiedDamage:{value:5}}},roll('s','MatrixResistTest',4),'a',flows,reducers);const branch=(soak as any).transaction.branches.a;expect(branch.stageId).toBe('done');expect(branch.derived.finalDamage).toBe(5);const damageConfirm=matrix.stages.find(s=>s.id==='soak')!.confirm!.find(c=>c.kind==='damage')!;expect(confirmationAvailable(damageConfirm,branch)).toBe(true)});
 it('shows placed marks on a successful hack but none on a miss',()=>{const hit=matrixDefenseReducer({transactionId:'t',branch:{} as any,origin:{hits:4} as any,roll:roll('d','OpposedBruteForceTest',1),stage:{} as any,data:{marks:2,modifiedDamage:{value:1,type:{value:'matrix'}}}});expect(hit.derived).toMatchObject({netHits:3,marksPlaced:2});const miss=matrixDefenseReducer({transactionId:'t',branch:{} as any,origin:{hits:2} as any,roll:roll('d','OpposedBruteForceTest',3),stage:{} as any,data:{marks:2}});expect(miss.derived).toMatchObject({netHits:0,marksPlaced:0,finalDamage:0})});
 it('threads a complex form and captures the fade',()=>{const{flows,reducers}=registry();const tx=createTransaction({kind:'ComplexFormTest',hits:4,modifiers:[]},'techno');tx.flowId='complex-form';const self:Branch={id:'self',kind:'self',actorUuid:'Actor.techno',name:'T',stageId:'',rolls:{},stageData:{},derived:{},confirmations:{}};self.stageId=complexForm.initialStage(self,tx.origin);tx.branches.self=self;expect(self.stageId).toBe('fade');const fade=routeFollowup(tx,{testClass:'FadeTest',actorUuid:'Actor.techno',data:{modifiedFade:{value:3,type:{value:'stun'}}}},roll('f','FadeTest',2),'Actor.techno',flows,reducers);expect(fade).toMatchObject({status:'captured',transaction:{complete:true,branches:{self:{stageId:'done',derived:{fadeHits:2,fadeDamage:3}}}}});const fadeConfirm=complexForm.stages.find(s=>s.id==='fade')!.confirm!.find(c=>c.kind==='fade')!;expect(confirmationAvailable(fadeConfirm,(fade as any).transaction.branches.self)).toBe(true)});
 it('compiles a sprite through opposition then fade',()=>{const{flows,reducers}=registry();const tx=createTransaction({kind:'CompileSpriteTest',hits:5,modifiers:[]},'techno');tx.flowId='sprite-compiling';const self:Branch={id:'self',kind:'self',actorUuid:'Actor.techno',name:'T',stageId:'compile-opposed',rolls:{},stageData:{},derived:{},confirmations:{}};tx.branches.self=self;const opposed=routeFollowup(tx,{testClass:'OpposedCompileSpriteTest',targetId:'self'},roll('o','OpposedCompileSpriteTest',2),'gm',flows,reducers);expect(opposed).toMatchObject({status:'captured',transaction:{branches:{self:{stageId:'fade',derived:{services:3}}}}});const fade=routeFollowup((opposed as any).transaction,{testClass:'FadeTest',targetId:'self',data:{modifiedFade:{value:2}}},roll('f','FadeTest',1),'techno',flows,reducers);expect(fade).toMatchObject({status:'captured',transaction:{complete:true,branches:{self:{stageId:'done',derived:{fadeDamage:2}}}}})});
 it('fadeResist reads modified fade',()=>{expect(fadeResistReducer({transactionId:'t',branch:{} as any,origin:{} as any,roll:roll('f','FadeTest',2),stage:{} as any,data:{modifiedFade:{value:4,type:{value:'physical'}}}}).derived).toMatchObject({fadeHits:2,fadeDamage:4,fadeType:'physical'})});
});
