import{describe,expect,it}from'vitest';
import{addTarget,createTransaction,invalidateEvent,migrate,RevisionConflict,setCalledShotAnnounced,setConfirmation,setDamageApplied,setDefense,setResistance}from'../src/core/transaction';
import{addSelectedTargets}from'../src/foundry/integration';
const roll=(kind:string,hits:number)=>({id:kind,kind,hits,modifiers:[],createdAt:1});
const attack=(hits:number,extra={})=>createTransaction({kind:'RangedAttackTest',hits,defenseTest:'PhysicalDefenseTest',resistanceTest:'PhysicalResistTest',modifiers:[],...extra},'attacker');
describe('transaction state machine',()=>{
 it('creates schema-v2 combat transactions',()=>{const tx=attack(3);expect(tx).toMatchObject({schemaVersion:2,flowId:'combat-attack',branches:{}})});
 it('imports the targets selected by the SR5 test',async()=>{const target={documentName:'Token',uuid:'Scene.s.Token.t',name:'Security Guard',actor:{uuid:'Actor.guard',name:'Guard'}};const out=await addSelectedTargets(attack(3),{targets:[target],data:{targetUuids:[]}},'attacker');expect(Object.values(out.branches)).toEqual([expect.objectContaining({kind:'target',actorUuid:'Actor.guard',tokenUuid:'Scene.s.Token.t',documentUuid:'Scene.s.Token.t',name:'Security Guard',stageId:'defense'})]);expect(out.events.at(-1)?.type).toBe('target.added')});
 it('keeps independent target branches and computes net hits/soak',()=>{let tx=attack(5);tx=addTarget(tx,0,'attacker',{id:'a',actorUuid:'Actor.a',name:'A'});tx=addTarget(tx,1,'attacker',{id:'b',actorUuid:'Actor.b',name:'B'});tx=setDefense(tx,2,'a','a',roll('defense',2),{modifiedDamage:10});tx=setResistance(tx,3,'a','a',roll('soak',4));expect(tx.branches.a).toMatchObject({stageId:'done',rolls:{defense:{hits:2},soak:{hits:4}},derived:{netHits:3,finalDamage:6}});expect(tx.branches.b!.stageId).toBe('defense')});
 it('skips defense after an attack with no hits',()=>{let tx=attack(0);tx=addTarget(tx,0,'u',{id:'a',actorUuid:'Actor.a',name:'A'});expect(tx.branches.a).toMatchObject({stageId:'done',derived:{netHits:0,finalDamage:0}})});
 it('skips defense when the system action defines none',()=>{let tx=createTransaction({kind:'SkillTest',hits:4,modifiers:[]},'u');tx=addTarget(tx,0,'u',{id:'a',actorUuid:'Actor.a',name:'A'});expect(tx.branches.a!.stageId).toBe('done')});
 it('skips resistance when defense negates all hits',()=>{let tx=attack(3);tx=addTarget(tx,0,'u',{id:'a',actorUuid:'Actor.a',name:'A'});tx=setDefense(tx,1,'u','a',roll('defense',3),{modifiedDamage:8});expect(tx.branches.a).toMatchObject({stageId:'done',derived:{netHits:0,finalDamage:0}})});
 it('skips resistance when no resist test exists',()=>{let tx=attack(4,{resistanceTest:undefined});tx=addTarget(tx,0,'u',{id:'a',actorUuid:'Actor.a',name:'A'});tx=setDefense(tx,1,'u','a',roll('defense',1),{modifiedDamage:9});expect(tx.branches.a).toMatchObject({stageId:'done',derived:{netHits:3,finalDamage:9}})});
 it('prefers the system-calculated final damage over its own subtraction',()=>{let tx=attack(5);tx=addTarget(tx,0,'u',{id:'a',actorUuid:'Actor.a',name:'A'});tx=setDefense(tx,1,'u','a',roll('defense',2),{modifiedDamage:10,damageType:'physical'});tx=setResistance(tx,2,'u','a',roll('soak',4),3);expect(tx.branches.a).toMatchObject({stageId:'done',derived:{soakHits:4,finalDamage:3,damageType:'physical'}})});
 it('records applied damage exactly once and only when complete',()=>{let tx=attack(5);tx=addTarget(tx,0,'u',{id:'a',actorUuid:'Actor.a',name:'A'});tx=setDefense(tx,1,'u','a',roll('defense',2),{modifiedDamage:10,damageType:'physical'});expect(()=>setDamageApplied(tx,2,'u','a',{value:6,type:'physical'})).toThrow('Damage is not final yet');tx=setResistance(tx,2,'u','a',roll('soak',4));tx=setDamageApplied(tx,3,'u','a',{value:6,type:'physical'});expect(tx.branches.a!.confirmations.damageApplied).toMatchObject({by:'u',payload:{value:6,type:'physical'}});expect(tx.events.at(-1)?.type).toBe('target.damageApplied');expect(()=>setDamageApplied(tx,4,'u','a',{value:6,type:'physical'})).toThrow('Damage already applied')});
 it('records generic confirmations exactly once',()=>{let tx=attack(0);tx=addTarget(tx,0,'u',{id:'a',actorUuid:'Actor.a',name:'A'});tx=setConfirmation(tx,1,'gm','a','ammoConfirmed',{rounds:3});expect(tx.branches.a!.confirmations.ammoConfirmed).toMatchObject({by:'gm',payload:{rounds:3}});expect(tx.events.at(-1)).toMatchObject({type:'confirmation.applied',payload:{branchId:'a',confirmationId:'ammoConfirmed'}});expect(()=>setConfirmation(tx,2,'gm','a','ammoConfirmed',{})).toThrow('already applied')});
 it('rejects stale revisions',()=>{const tx=createTransaction({kind:'SkillTest',modifiers:[]},'u');expect(()=>addTarget(tx,2,'u',{actorUuid:'a',name:'a'})).toThrow(RevisionConflict)});
 it('does not delete invalidated history',()=>{let tx=createTransaction({kind:'SkillTest',modifiers:[]},'u');const id=tx.events[0]!.id;tx=invalidateEvent(tx,0,'gm',id,'wrong actor');expect(tx.events).toHaveLength(2);expect(tx.events[0]!.invalidated?.reason).toBe('wrong actor')});
 it('toggles the announced called-shot flag',()=>{let tx=createTransaction({kind:'RangedAttackTest',modifiers:[]},'u');tx=setCalledShotAnnounced(tx,0,'gm',true);expect(tx.calledShotAnnounced).toBe(true);expect(tx.events.at(-1)).toMatchObject({type:'calledShot.announced',payload:{value:true}});tx=setCalledShotAnnounced(tx,1,'gm',false);expect(tx.calledShotAnnounced).toBeUndefined()});
});
describe('schema migration',()=>{
 it('migrates v1 targets, stages, rolls, data, derived values and confirmations',()=>{const defense=roll('defense',2),soak=roll('soak',4);const v1:any={schemaVersion:1,id:'tx',revision:4,authorId:'u',createdAt:1,updatedAt:2,origin:roll('attack',5),targets:{a:{id:'a',actorUuid:'Actor.a',tokenUuid:'Token.a',name:'A',stage:'complete',defense,resistance:soak,defenseData:{against:true},netHits:3,baseDamage:8,modifiedDamage:10,soakHits:4,finalDamage:6,damageType:'physical',damageApplied:{at:3,by:'gm',value:6,type:'physical'}}},events:[],complete:true};const tx=migrate(v1);expect(tx).toMatchObject({schemaVersion:2,flowId:'combat-attack',id:'tx',revision:4,complete:true,branches:{a:{id:'a',kind:'target',actorUuid:'Actor.a',tokenUuid:'Token.a',stageId:'done',rolls:{defense,soak},stageData:{defense:{against:true}},derived:{netHits:3,baseDamage:8,modifiedDamage:10,soakHits:4,finalDamage:6,damageType:'physical'},confirmations:{damageApplied:{at:3,by:'gm',payload:{value:6,type:'physical'}}}}}});expect((tx as any).targets).toBeUndefined()});
 it.each([['created','defense'],['defending','defense'],['defended','soak'],['resisting','soak'],['complete','done']])('maps v1 stage %s to %s',(from,to)=>{const tx=migrate({schemaVersion:1,id:'tx',revision:0,authorId:'u',createdAt:1,updatedAt:1,origin:roll('attack',1),targets:{a:{id:'a',actorUuid:'Actor.a',name:'A',stage:from}},events:[],complete:false});expect(tx.branches.a!.stageId).toBe(to)});
 it('is idempotent for v2 and rejects unknown schemas',()=>{const tx=attack(1);expect(migrate(tx)).toBe(tx);expect(()=>migrate({...tx,schemaVersion:3})).toThrow('No migration from schema 3')});
});
