import{describe,expect,it}from'vitest';import{FlowRegistry}from'../src/core/flows/registry';import{routeFollowup}from'../src/core/flows/router';import{chaseOpposedReducer,chaseRamDamage,droneInfiltration,dronePerception,ramDamage,vehiclePilot}from'../src/core/flows/specs/vehicle';import{genericOpposed,genericSimple}from'../src/core/flows/specs/generic';import{createReducerRegistry}from'../src/core/reducers';import{addTarget,createTransaction}from'../src/core/transaction';import type{RollRecord}from'../src/types';
const roll=(id:string,kind:string,hits:number):RollRecord=>({id,kind,hits,modifiers:[],createdAt:1});
const setup=()=>{const flows=new FlowRegistry(),reducers=createReducerRegistry();reducers.register('chaseOpposed',chaseOpposedReducer);flows.register(vehiclePilot);flows.register(dronePerception);flows.register(droneInfiltration);flows.register(genericOpposed);flows.register(genericSimple);return{flows,reducers}};
describe('vehicle flows',()=>{
 it('matches pilot and drone tests before the generic fallbacks',()=>{const{flows}=setup();expect(flows.match({testClass:'PilotVehicleTest',data:{}})?.id).toBe('vehicle-pilot');expect(flows.match({testClass:'DronePerceptionTest',data:{}})?.id).toBe('drone-perception');expect(flows.match({testClass:'DroneInfiltrationTest',data:{}})?.id).toBe('drone-infiltration');expect(flows.match({testClass:'SkillTest',data:{}})?.id).toBe('generic-simple')});
 it('leaves opposed pilot tests to the generic opposed flow',()=>{const{flows}=setup();expect(flows.match({testClass:'PilotVehicleTest',data:{opposed:{test:'PilotVehicleTest'}}})?.id).toBe('generic-opposed')});
 it('runs the chase stage as an opposed pilot test',()=>{const{flows,reducers}=setup();let tx=createTransaction({kind:'PilotVehicleTest',hits:4,modifiers:[]},'driver');tx.flowId='vehicle-pilot';tx=addTarget(tx,0,'driver',{id:'t',actorUuid:'Actor.t',name:'Verfolger'});tx.branches.t!.stageId=vehiclePilot.initialStage(tx.branches.t!,tx.origin);expect(tx.branches.t!.stageId).toBe('chase');const chased=routeFollowup(tx,{testClass:'PilotVehicleTest',targetId:'t'},roll('c','PilotVehicleTest',1),'other',flows,reducers);expect(chased).toMatchObject({status:'captured',transaction:{complete:true,branches:{t:{stageId:'done',derived:{netHits:3,chaseShift:3}}}}})});
 it('computes GRW ram damage bands and chase ram values',()=>{expect(ramDamage(11,10)).toBe(6);expect(ramDamage(11,50)).toBe(11);expect(ramDamage(11,200)).toBe(22);expect(ramDamage(11,300)).toBe(33);expect(chaseRamDamage(11,2)).toEqual({target:13,self:6});expect(chaseRamDamage(0,-1)).toEqual({target:0,self:0})});
});
