import type {DiceFlowAPI} from '../api';import{flows}from'../core/flows/registry';import{resolvedTestClasses}from'../core/flows/spec';import{HEAL_TRACKS,healingAmount}from'../core/flows/specs/general';import{DAMAGE_TRACKS,type Branch,type Transaction}from'../types';import{setCalledShotAnnounced,setConfirmation,setDamageApplied}from'../core/transaction';import{commitMutation}from'./integration';import{getTransaction}from'./store';
function notify(kind:'warn'|'error',key:string){ui.notifications[kind](game.i18n.localize(key))}
export interface ConfirmationOptions {healTrack?:string}
type ConfirmationHandler=(message:any,target:Branch,options?:ConfirmationOptions)=>Promise<unknown>;export class ConfirmationActionRegistry{private handlers=new Map<string,ConfirmationHandler>();register(kind:string,handler:ConfirmationHandler){if(this.handlers.has(kind))throw new Error(`Confirmation handler already registered: ${kind}`);this.handlers.set(kind,handler);return()=>this.handlers.delete(kind)}get(kind:string){const handler=this.handlers.get(kind);if(!handler)throw new Error(game.i18n.localize('SDF.Error.MissingConfirmationHandler'));return handler}}
export const confirmationActions=new ConfirmationActionRegistry();
export function getSystemTestData(message:any){return message.getFlag('shadowrun5e','TestData')??message.getFlag('shadowrun5e','test')}
async function ownedActor(target:Branch){const actor=await fromUuid(target.actorUuid);if(!actor){notify('error','SDF.Error.MissingTargetActor');return}if(!game.user.isGM&&!actor.testUserPermission?.(game.user,'OWNER')){notify('warn','SDF.Error.NoActorOwner');return}return actor}
export interface DefenseSeed {activeDefense?:string;cover?:number}
async function executeFollowup(message:any,target:Branch,againstData:any,className:string,seed?:DefenseSeed){const actor=await ownedActor(target);if(!actor)return;const TestClass=game.shadowrun5e?.tests?.[className];if(!TestClass){notify('error','SDF.Error.MissingTestClass');return}againstData.targetUuids=[target.tokenUuid??target.actorUuid];const data=await TestClass._getOpposedActionTestData?.(againstData,actor,message.id)??await TestClass._getResistActionTestData?.(againstData,actor,message.id);if(!data)return;data.previousMessageId=message.id;data.sr5DiceFlow={messageId:message.id,targetId:target.id,step:target.stageId==='defense'?'defense':'resistance'};const test=new TestClass(data,{source:actor},{showDialog:true,showMessage:true});if(seed){if(seed.activeDefense)test.data.activeDefense=seed.activeDefense;if(seed.cover)test.data.cover=seed.cover}await test.execute()}
async function defend(message:any,target:Branch,seed?:DefenseSeed,className?:string){const flag=getSystemTestData(message);const againstData=foundry.utils.deepClone(flag?.data);if(!againstData){notify('error','SDF.Error.MissingSystemTest');return}const cls=className??againstData.opposed?.test;if(!cls){notify('warn','SDF.Error.NoDefenseTest');return}await executeFollowup(message,target,againstData,cls,seed)}
function defenseTestClass(tx:Transaction,target:Branch){try{const spec=flows.get(tx.flowId),stage=spec.stages.find(value=>value.id===target.stageId);return stage?resolvedTestClasses(stage,tx.origin)[0]:undefined}catch{return undefined}}
function buildDamage(value:number,type:string){const damage:any=game.shadowrun5e?.data?.createData?.('damage',{})??{base:0,value:0,type:{base:'',value:''},element:{base:'',value:''},ap:{base:0,value:0,mod:[]},mod:[]};damage.base=value;damage.value=value;damage.type.base=type;damage.type.value=type;return damage}
async function applyDamage(message:any,target:Branch){if(target.stageId!=='done'||target.confirmations.damageApplied){notify('warn','SDF.Error.DamageAlreadyApplied');return}const value=Number(target.derived.finalDamage??0);const type=String(target.derived.damageType??'');if(value<=0||!DAMAGE_TRACKS.includes(type)){notify('warn','SDF.Error.NoApplicableDamage');return}const actor=await ownedActor(target);if(!actor)return;await actor.addDamage(buildDamage(value,type));const tx=await getTransaction(message);if(!tx||!tx.branches[target.id])return;const updated=setDamageApplied(tx,tx.revision,game.user.id,target.id,{value,type});await commitMutation(message,tx,updated,'damageApplied',{targetId:target.id,value,type,actorUuid:target.actorUuid})}
confirmationActions.register('damage',applyDamage);
async function applyDrain(message:any,target:Branch){if(target.confirmations.drainApplied){notify('warn','SDF.Error.DrainAlreadyApplied');return}const value=Number(target.derived.drainDamage??0);const type=String(target.derived.drainType||'stun');if(value<=0||!DAMAGE_TRACKS.includes(type)){notify('warn','SDF.Error.NoDrainDamage');return}const actor=await ownedActor(target);if(!actor)return;await actor.addDamage(buildDamage(value,type));const tx=await getTransaction(message);if(!tx||!tx.branches[target.id])return;const payload={value,type};const updated=setConfirmation(tx,tx.revision,game.user.id,target.id,'drainApplied',payload);await commitMutation(message,tx,updated,'confirm',{branchId:target.id,confirmationId:'drainApplied',kind:'drain',value:payload,actorUuid:target.actorUuid})}
confirmationActions.register('drain',applyDrain);
async function applyFade(message:any,target:Branch){if(target.confirmations.fadeApplied){notify('warn','SDF.Error.FadeAlreadyApplied');return}const value=Number(target.derived.fadeDamage??0);const type=String(target.derived.fadeType||'stun');if(value<=0||!DAMAGE_TRACKS.includes(type)){notify('warn','SDF.Error.NoFadeDamage');return}const actor=await ownedActor(target);if(!actor)return;await actor.addDamage(buildDamage(value,type));const tx=await getTransaction(message);if(!tx||!tx.branches[target.id])return;const payload={value,type};const updated=setConfirmation(tx,tx.revision,game.user.id,target.id,'fadeApplied',payload);await commitMutation(message,tx,updated,'confirm',{branchId:target.id,confirmationId:'fadeApplied',kind:'fade',value:payload,actorUuid:target.actorUuid})}
confirmationActions.register('fade',applyFade);
// The system's First Aid test carries no track, so the healer picks it on the card; without a
// valid choice nothing is mutated.
async function applyHeal(message:any,target:Branch,options?:ConfirmationOptions){if(target.confirmations.healApplied){notify('warn','SDF.Error.HealAlreadyApplied');return}const tx=await getTransaction(message);const amount=healingAmount(tx?.origin);if(amount<=0){notify('warn','SDF.Error.NoHealing');return}const track=String(options?.healTrack??'');if(!HEAL_TRACKS.includes(track)){notify('warn','SDF.Error.NoHealTrack');return}const actor=await ownedActor(target);if(!actor)return;if(!actor.healDamage){notify('error','SDF.Error.NoHealApi');return}await actor.healDamage(track,amount);if(!tx||!tx.branches[target.id])return;const payload={amount,track};const updated=setConfirmation(tx,tx.revision,game.user.id,target.id,'healApplied',payload);await commitMutation(message,tx,updated,'confirm',{branchId:target.id,confirmationId:'healApplied',kind:'heal',value:payload,actorUuid:target.actorUuid})}
confirmationActions.register('heal',applyHeal);
const pendingAmmoConfirmations=new Set<string>();
async function applyAmmo(message:any,target:Branch){if(target.confirmations.ammoConfirmed){notify('warn','SDF.Error.AmmoAlreadyConfirmed');return}const combat=(target.stageData.origin as any)?.combat,ammo=combat?.ammo,rounds=Math.max(0,Number(ammo?.rounds)||0);if(!ammo?.deferred||!ammo.itemUuid||rounds<=0){notify('warn','SDF.Error.NoPendingAmmo');return}const key=`${message.uuid??message.id}:${target.id}`;if(pendingAmmoConfirmations.has(key))return;pendingAmmoConfirmations.add(key);try{const actor=await ownedActor(target);if(!actor)return;const item=await fromUuid(ammo.itemUuid);if(!item?.useAmmo){notify('error','SDF.Error.MissingAmmoItem');return}const before=Number(item.system?.ammo?.current?.value);await item.useAmmo(rounds);const after=Number(item.system?.ammo?.current?.value),payload={itemUuid:ammo.itemUuid,rounds,before,after};const tx=await getTransaction(message);if(!tx||!tx.branches[target.id])return;const updated=setConfirmation(tx,tx.revision,game.user.id,target.id,'ammoConfirmed',payload);await commitMutation(message,tx,updated,'confirm',{branchId:target.id,confirmationId:'ammoConfirmed',kind:'ammo',value:payload,actorUuid:target.actorUuid})}finally{pendingAmmoConfirmations.delete(key)}}
confirmationActions.register('ammo',applyAmmo);
const pendingInitiativeConfirmations=new Set<string>();
async function applyInitiative(message:any,target:Branch){if(target.confirmations.initiativeApplied){notify('warn','SDF.Error.InitiativeAlreadyApplied');return}const iniMod=Number(target.derived.iniMod);if(!Number.isFinite(iniMod)||iniMod===0){notify('warn','SDF.Error.NoInitiativeCost');return}if(!game.combat){notify('warn','SDF.Error.NoActiveCombat');return}const key=`${message.uuid??message.id}:${target.id}`;if(pendingInitiativeConfirmations.has(key))return;pendingInitiativeConfirmations.add(key);try{const actor=await ownedActor(target);if(!actor)return;await actor.changeCombatInitiative(iniMod);const payload={iniMod};const tx=await getTransaction(message);if(!tx||!tx.branches[target.id])return;const updated=setConfirmation(tx,tx.revision,game.user.id,target.id,'initiativeApplied',payload);await commitMutation(message,tx,updated,'confirm',{branchId:target.id,confirmationId:'initiativeApplied',kind:'initiative',value:payload,actorUuid:target.actorUuid})}finally{pendingInitiativeConfirmations.delete(key)}}
confirmationActions.register('initiative',applyInitiative);
async function resist(message:any,target:Branch){const defenseData=foundry.utils.deepClone(target.stageData.defense);if(!defenseData){notify('error','SDF.Error.MissingDefenseData');return}const className=defenseData.against?.opposed?.resist?.test;if(!className){notify('warn','SDF.Error.NoResistTest');return}await executeFollowup(message,target,defenseData,className)}
async function conjureOpposed(message:any,tx:Transaction,target:Branch){if(!game.user.isGM){notify('warn','SDF.Error.GMOnly');return}const className=defenseTestClass(tx,target);if(!className){notify('error','SDF.Error.MissingTestClass');return}const TestClass=game.shadowrun5e?.tests?.[className];if(!TestClass?._getOpposedActionTestData){notify('error','SDF.Error.MissingTestClass');return}const flag=getSystemTestData(message),againstData=foundry.utils.deepClone(flag?.data);if(!againstData){notify('error','SDF.Error.MissingSystemTest');return}const bootstrap=TestClass._resolveOpposedBootstrapDocument?await TestClass._resolveOpposedBootstrapDocument(againstData):await fromUuid(target.actorUuid);if(!bootstrap){notify('error','SDF.Error.NoConjureTarget');return}const data=await TestClass._getOpposedActionTestData(againstData,bootstrap,message.id);if(!data){notify('error','SDF.Error.MissingSystemTest');return}data.previousMessageId=message.id;data.sr5DiceFlow={messageId:message.id,targetId:target.id,step:target.stageId};const test=new TestClass(data,{source:bootstrap},{showDialog:true,showMessage:true});await test.execute()}
async function conjureDrain(message:any,target:Branch){const actor=await ownedActor(target);if(!actor)return;const flag=getSystemTestData(message);if(!flag?.data?.drainReady&&!flag?.data?.fadeReady){notify('warn','SDF.Error.ConjuringNotConcluded');return}const creator=game.shadowrun5e?.test;if(!creator?.fromMessage){notify('error','SDF.Error.MissingTestClass');return}const test=await creator.fromMessage(message.id,{showDialog:true});if(!test){notify('error','SDF.Error.MissingSystemTest');return}await test.populateDocuments?.();await test.executeFollowUpTest()}
async function runStage(message:any,tx:Transaction,target:Branch,stageId:string){const spec=flows.get(tx.flowId),stage=spec.stages.find(value=>value.id===stageId);if(!stage||target.stageId!==stageId)throw new Error(game.i18n.localize('SDF.Error.InvalidStage'));if(stage.trigger!=='button')throw new Error(game.i18n.localize('SDF.Error.StageNotManual'));const className=resolvedTestClasses(stage,tx.origin)[0];if(!className){notify('error','SDF.Error.MissingTestClass');return}const system=getSystemTestData(message),prior=Object.values(target.stageData).at(-1),againstData=foundry.utils.deepClone(stageId==='defense'||stageId==='opposed'?system?.data:prior??system?.data);if(!againstData){notify('error','SDF.Error.MissingSystemTest');return}await executeFollowup(message,target,againstData,className)}
export function normalizeCardAction(action?:string){if(action==='defend')return{action:'run-stage',stageId:'defense'};if(action==='resist')return{action:'run-stage',stageId:'soak'};if(action==='apply-damage')return{action:'confirm',confirmId:'damageApplied',confirmKind:'damage'};return{action}}
async function addCurrentTargets(api:DiceFlowAPI,message:any){const selected=[...(game.user?.targets??[])];if(selected.length===0){notify('warn','SDF.Error.SelectTarget');return}let tx=await getTransaction(message);if(!tx)return;for(const token of selected){const document=token.document??token;const actor=document.actor;if(!actor)continue;const duplicate=Object.values(tx.branches).some(target=>target.kind==='target'&&target.actorUuid===actor.uuid&&target.tokenUuid===document.uuid);if(duplicate)continue;tx=await api.addTarget(message,{actorUuid:actor.uuid,tokenUuid:document.uuid,documentUuid:document.uuid,name:document.name??actor.name},tx.revision)}}
async function announceCalledShot(message:any,tx:Transaction){if(!(game.user.isGM||message.isAuthor)){notify('warn','SDF.Error.NoPermission');return}const updated=setCalledShotAnnounced(tx,tx.revision,game.user.id,!tx.calledShotAnnounced);await commitMutation(message,tx,updated,'calledShot',{value:updated.calledShotAnnounced??false})}
export async function handleCardAction(api:DiceFlowAPI,message:any,element:HTMLElement){const normalized=normalizeCardAction(element.dataset.sdfAction),tx=await getTransaction(message);if(!tx)return;try{if(normalized.action==='add-target')return await addCurrentTargets(api,message);if(normalized.action==='announce-called-shot')return await announceCalledShot(message,tx);const target=tx.branches[element.dataset.targetId??''];if(!target){notify('error','SDF.Error.MissingTarget');return}if(element.dataset.sdfAction==='defend'){const coverEl=element.closest('.sdf-target')?.querySelector('[data-sdf-cover]')as HTMLSelectElement|null;return await defend(message,target,{activeDefense:element.dataset.activeDefense||undefined,cover:Number(coverEl?.value)||0},defenseTestClass(tx,target))}if(element.dataset.sdfAction==='resist')return await resist(message,target);if(element.dataset.sdfAction==='conjure-opposed')return await conjureOpposed(message,tx,target);if(element.dataset.sdfAction==='conjure-drain')return await conjureDrain(message,target);if(normalized.action==='run-stage')return await runStage(message,tx,target,element.dataset.stageId??normalized.stageId??target.stageId);if(normalized.action==='confirm'){const id=element.dataset.confirmId??normalized.confirmId,kind=element.dataset.confirmKind??normalized.confirmKind;if(!id||!kind)throw new Error(game.i18n.localize('SDF.Error.InvalidConfirmation'));if(element.dataset.sdfAction==='confirm'){const spec=flows.get(tx.flowId),declared=spec.stages.flatMap(value=>value.confirm??[]).some(value=>value.id===id&&value.kind===kind);if(!declared)throw new Error(game.i18n.localize('SDF.Error.InvalidConfirmation'))}const trackEl=element.closest('.sdf-target')?.querySelector('[data-sdf-heal-track]')as HTMLSelectElement|null;return await confirmationActions.get(kind)(message,target,{healTrack:trackEl?.value||undefined})}}catch(error:any){console.error('sr5-dice-flow | Card action failed',error);ui.notifications.error(error?.message??game.i18n.localize('SDF.Error.ActionFailed'))}}
