import{ECONOMY_ACTION_TYPES,recordAction,type ActionType,type EconomyState}from'../core/economy';import{MODULE_ID}from'../types';import{stableRollId}from'./extract';import{requestId,socket}from'./socket';
export const ECONOMY_FLAG='economy';
export const combatPass=(combat:any)=>Number(combat?.pass??combat?.system?.pass??1)||1;
export interface EconomyPayload {combatId:string;combatantId:string;actorUuid?:string;type:ActionType;rollId:string;label?:string;iniMod?:number;round:number;pass:number}
function combatantForActor(combat:any,actor:any){if(!combat||!actor)return undefined;return combat.getActorCombatant?.(actor)??combat.combatants?.find?.((entry:any)=>entry.actor?.uuid===actor.uuid||entry.actorId===actor.id)}
export interface EconomyOverride {type:ActionType;iniMod?:number;label?:string}
export function economyPayload(test:any,override?:EconomyOverride):EconomyPayload|undefined{const type=override?.type??test?.data?.action?.type;if(!ECONOMY_ACTION_TYPES.includes(type))return;const combat=game.combat;if(!combat)return;const actor=test.actor??test.source;const combatant=combatantForActor(combat,actor);if(!combatant)return;const iniMod=override?.iniMod??Number(test?.data?.action?.initiative_mod);return{combatId:combat.id,combatantId:combatant.id,actorUuid:actor?.uuid,type,rollId:stableRollId(test),label:override?.label??test?.data?.title,iniMod:Number.isFinite(iniMod)&&iniMod!==0?iniMod:undefined,round:Number(combat.round)||0,pass:combatPass(combat)}}
export async function applyEconomyMutation(payload:EconomyPayload){const combat=game.combats?.get(payload.combatId)??game.combat;if(!combat)return;const combatant=combat.combatants?.get(payload.combatantId);if(!combatant)return;const current=combatant.getFlag(MODULE_ID,ECONOMY_FLAG)as EconomyState|undefined;const next=recordAction(current,Number(payload.round)||Number(combat.round)||0,Number(payload.pass)||combatPass(combat),{rollId:payload.rollId,type:payload.type,label:payload.label,iniMod:payload.iniMod});if(current&&current.round===next.round&&current.pass===next.pass&&current.applied.length===next.applied.length)return;await combatant.setFlag(MODULE_ID,ECONOMY_FLAG,next)}
export async function recordEconomyFromTest(test:any,override?:EconomyOverride){try{const payload=economyPayload(test,override);if(!payload)return;if(game.user.isGM)await applyEconomyMutation(payload);else await socket.request('',{transactionId:'',expectedRevision:0,action:'economy',payload:payload as any,requestId:requestId(),userId:game.user.id})}catch(error){console.warn(`${MODULE_ID} | economy tracking failed`,error)}}
export function resetStaleEconomy(combat:any){if(!combat||!game.user.isGM)return;const round=Number(combat.round)||0,pass=combatPass(combat);for(const combatant of combat.combatants??[]){const state=combatant.getFlag(MODULE_ID,ECONOMY_FLAG)as EconomyState|undefined;if(state&&(state.round!==round||state.pass!==pass))void combatant.unsetFlag(MODULE_ID,ECONOMY_FLAG)}}
