import{MODULE_ID,type Transaction}from'../types';import{buildPendingEffects}from'../core/effects';import{setPendingEffects,type PendingEffectEntry}from'../core/transaction';import{getTransaction,saveTransaction}from'./store';import{requestId,socket}from'./socket';
// Local copy of integration.ts' marker accessor to avoid an import cycle (integration imports us).
const marker=(data:any)=>data?.sr5DiceFlow??data?.following?.sr5DiceFlow;
function collectEffects(test:any):any[]|undefined{const data=test?.effects?._collectTargetActorEffectsData?.();return Array.isArray(data)&&data.length?data:undefined}
async function commitPending(message:any,tx:Transaction,entries:PendingEffectEntry[],actorUuid?:string){if(game.user.isGM||message.isAuthor){await saveTransaction(message,setPendingEffects(tx,tx.revision,game.user.id,entries));return}await socket.request(message.uuid,{transactionId:tx.id,expectedRevision:tx.revision,action:'pendingEffects',payload:{entries,actorUuid},requestId:requestId(),userId:game.user.id})}
const pending=(effectsData:any[],item:any)=>buildPendingEffects(effectsData,{itemUuid:item?.uuid,itemName:item?.name,source:'deferred'});
// Unopposed success: SuccessTest.afterSuccess only loops createTargetActorEffects over this.targets
// (verified in 0.36.x), so a full defer may skip wrapped() entirely. Partial branch coverage falls
// back to the system so no target ever loses its effects silently.
async function deferUnopposed(test:any){const targets=[...(test.targets??[])].filter(target=>target?.actor);if(test.opposing||test.opposed||!targets.length)return false;const effectsData=collectEffects(test);if(!effectsData)return false;const message=test.data?.messageUuid?await fromUuid(test.data.messageUuid):undefined;const tx=await getTransaction(message);if(!tx)return false;const entries:PendingEffectEntry[]=[];for(const target of targets){const actorUuid=target.actor.uuid;const branch=Object.values(tx.branches).find(value=>value.kind==='target'&&value.actorUuid===actorUuid&&value.stageData.effects===undefined);if(branch)entries.push({branchId:branch.id,effects:pending(effectsData,test.item),count:effectsData.length})}if(entries.length!==targets.length)return false;await commitPending(message,tx,entries);return true}
// Opposed failure: the defender failed, the original item's targeted effects hit the defender
// (OpposedTest.afterFailure; the item resolves via sourceItemUuid). Routed to the defender's branch.
async function deferOpposed(test:any){const against=test.against,actorUuid=test.actor?.uuid;if((against===undefined&&!test.opposing)||!actorUuid)return false;const effectsData=collectEffects(test);if(!effectsData)return false;const flow=marker(test.data),previousId=flow?.messageId??test.data?.previousMessageId;if(!previousId)return false;const message=game.messages?.get(previousId)??await fromUuid(previousId);const tx=await getTransaction(message);if(!tx)return false;const branch=(flow?.targetId?tx.branches[flow.targetId]:undefined)??Object.values(tx.branches).find(value=>value.kind==='target'&&value.actorUuid===actorUuid);if(!branch||branch.stageData.effects!==undefined)return false;await commitPending(message,tx,[{branchId:branch.id,effects:pending(effectsData,test.item),count:effectsData.length}],branch.actorUuid);return true}
function wrap(path:string,defer:(test:any)=>Promise<boolean>){window.libWrapper.register(MODULE_ID,path,async function(this:any,wrapped:(...args:any[])=>Promise<any>,...args:any[]){if(!game.settings.get(MODULE_ID,'deferEffects'))return wrapped(...args);try{if(await defer(this))return}catch(error){console.warn(`${MODULE_ID} | Deferred effect application unavailable; using system behavior`,error)}return wrapped(...args)},'MIXED')}
export function installEffectsWrappers(){if(!globalThis.window?.libWrapper)return;const tests=game.shadowrun5e?.tests;if(tests?.SuccessTest)try{wrap('game.shadowrun5e.tests.SuccessTest.prototype.afterSuccess',deferUnopposed)}catch(error){console.warn(`${MODULE_ID} | Cannot wrap afterSuccess; effects apply natively`,error)}
if(tests?.OpposedTest)try{wrap('game.shadowrun5e.tests.OpposedTest.prototype.afterFailure',deferOpposed)}catch(error){console.warn(`${MODULE_ID} | Cannot wrap afterFailure; effects apply natively`,error)}}
export const effectsInternals={deferUnopposed,deferOpposed,collectEffects};
