import{extractors}from'../core/flows/registry';import type{FlowOrigin}from'../core/flows/spec';import{ammoState}from'./ammo';import{CALLED_SHOT_MODIFIER}from'../core/calledshots';import{isSecretRollMode,sanitizeRoll}from'./security';import type{Modifier,RollRecord}from'../types';
const ids=new WeakMap<object,string>();const uid=()=>globalThis.crypto?.randomUUID?.()??`${Date.now()}-${Math.random().toString(36).slice(2)}`;const combatBefore=new WeakMap<object,{ammo?:number;recoil?:number}>();
export function captureCombatBefore(test:any){if(!test||typeof test!=='object')return;combatBefore.set(test,{ammo:Number(test.item?.system?.ammo?.current?.value),recoil:Number(test.actor?.recoil?.())})}
export function combatOriginExtractor(origin:FlowOrigin){const test=origin.test,data=origin.data??{},before=test&&combatBefore.get(test),deferred=ammoState(test),ammo=data.fireMode?{before:Number.isFinite(before?.ammo)?before!.ammo:undefined,after:Number(test?.item?.system?.ammo?.current?.value),max:Number(test?.item?.system?.ammo?.current?.max),plannedAfter:deferred?.plannedAfter,rounds:deferred?.rounds,deferred:Boolean(deferred?.deferred),fallback:Boolean(deferred?.fallback),itemUuid:deferred?.itemUuid}:undefined,recoil=data.fireMode?{before:Number.isFinite(before?.recoil)?before!.recoil:undefined,after:Number(test?.actor?.recoil?.()),compensation:Number(test?.item?.totalRecoilCompensation)}:undefined;const groups:Record<string,unknown[]>={};for(const change of data.pool?.changes??[]){const text=`${change.name??''} ${change.source??''}`.toLowerCase();const group=/range|reichweite/.test(text)?'range':/recoil|rückstoß|rueckstoss/.test(text)?'recoil':/wound|wunde/.test(text)?'wounds':/environment|umwelt|sicht|licht|wind/.test(text)?'environment':'other';(groups[group]??=[]).push({name:change.name,value:Number(change.value)||0,source:change.source,enabled:change.enabled!==false&&!change.invalidated})}const calledShotChange=(data.pool?.changes??[]).find((change:any)=>change.name===CALLED_SHOT_MODIFIER&&change.enabled!==false&&Number(change.value)!==0),declaredShot=data.calledShot,calledShot=(declaredShot||calledShotChange)?{key:declaredShot?.key,label:declaredShot?.label,mod:Math.abs(Number(calledShotChange?.value)||declaredShot?.mod||4)}:undefined;return{combat:{fireMode:data.fireMode?{label:data.fireMode.label,rounds:Number(data.fireMode.value)||0,defense:Number(data.fireMode.defense)||0,action:data.fireMode.action,suppression:Boolean(data.fireMode.suppression)}:undefined,ammo,recoil,range:Number(data.range)||0,targetRanges:(data.targetRanges??[]).map((target:any)=>({tokenUuid:target.tokenUuid,distance:Number(target.distance)||0,label:target.range?.label,modifier:Number(target.range?.modifier)||0})),reach:data.reach===undefined?undefined:Number(data.reach),calledShot,poolGroups:groups},selfDerived:deferred?.deferred?{ammoPending:deferred.rounds}:undefined}}
export const testClass=(test:any)=>String(test?.data?.type??test?.constructor?.name??'SuccessTest');
export const testActorUuid=(test:any)=>test?.actor?.uuid??test?.source?.uuid;
export const stableRollId=(test:any)=>{const explicit=test?.data?.uuid??test?.data?.id??test?.rolls?.at(-1)?.id;if(explicit)return String(explicit);if(test&&typeof test==='object'){const found=ids.get(test);if(found)return found;const id=uid();ids.set(test,id);return id}return uid()};
function localize(value:unknown){const key=String(value??'');return game.i18n.has?.(key)?game.i18n.localize(key):key}
export function poolModifiers(test:any):Modifier[]{return(test.data?.pool?.changes??[]).map((change:any,index:number)=>({id:`system-pool-${index}`,label:localize(change.name),value:Number(change.value)||0,source:change.source||game.i18n.localize('SDF.SystemSource'),condition:change.enabled===false?game.i18n.localize('SDF.Disabled'):change.invalidated?game.i18n.localize('SDF.Masked'):undefined,fingerprint:`system:${index}:${change.name}:${change.value}`}))}
export function rollRecord(test:any,rollMode:string):RollRecord{const secret=isSecretRollMode(rollMode);const roll=test.rolls?.at(-1);const damage=test.data?.damage;return{id:stableRollId(test),kind:testClass(test),title:localize(test.data?.title),actorUuid:testActorUuid(test),actorName:test.actor?.name??test.source?.name,itemName:test.item?.name,basePool:secret?undefined:test.data?.pool?.base,pool:secret?undefined:test.data?.pool?.value,hits:secret?undefined:test.data?.values?.hits?.value,rawHits:secret?undefined:test.data?.values?.hits?.base,limit:secret?undefined:test.hasLimit?test.data?.limit?.value:undefined,threshold:secret?undefined:test.hasThreshold?test.data?.threshold?.value:undefined,glitches:secret?undefined:test.data?.values?.glitches?.value,defenseTest:test.data?.opposed?.test||undefined,resistanceTest:test.data?.opposed?.resist?.test||undefined,baseDamage:damage?.value??damage?.base,damageType:damage?.type?.value,edge:test.data?.pushTheLimit||test.data?.secondChance?{pushTheLimit:Boolean(test.data?.pushTheLimit)||undefined,secondChance:Boolean(test.data?.secondChance)||undefined}:undefined,actionSkill:test.data?.action?.skill||undefined,rollMode,rollJson:sanitizeRoll(roll,rollMode),modifiers:secret?[]:poolModifiers(test),createdAt:Date.now()}}
export async function extractOrigin(names:string[],origin:FlowOrigin){return Object.assign({},...await Promise.all(names.map(name=>extractors.get(name)(origin))))}
export const cloneTestData=(test:any)=>foundry.utils.deepClone(test.data);
