import{extractors}from'../core/flows/registry';import type{FlowOrigin}from'../core/flows/spec';import{effectList,isSelfEffect,isTargetedEffect}from'../core/flows/specs/items';import{buildPendingEffects}from'../core/effects';import{createTransaction,setPendingEffects,type PendingEffectEntry}from'../core/transaction';import{MODULE_ID}from'../types';import{cardSections}from'./card-sections';import{addSelectedTargets}from'./integration';import{extractOrigin}from'./extract';import{createMessage}from'./store';
const effectMeta=(effect:any)=>({name:effect?.name,img:effect?.img,applyTo:effect?.system?.applyTo,disabled:Boolean(effect?.disabled)});
export function itemUseExtractor(origin:FlowOrigin){const item=origin.test?.item;if(!item)return{};const effects=effectList(item),self=effects.filter(isSelfEffect);return{item:{name:item.name,img:item.img,uuid:item.uuid,type:item.type,hasRoll:Boolean(item.hasRoll),blast:item.isAreaOfEffect?.()?item.getBlastData?.():undefined,targetedEffects:effects.filter(isTargetedEffect).map(effectMeta),selfEffects:self.map(effectMeta),activeSelfEffects:effects.filter(effect=>effect?.system?.applyTo==='actor'&&!effect?.disabled).map(effectMeta)},selfDerived:self.length?{selfPendingEffects:self.length}:undefined}}
export function registerItemPresentation(){if(!extractors.has('itemUse'))extractors.register('itemUse',itemUseExtractor);if(!cardSections.has('itemUse'))cardSections.register('itemUse',({transaction,escape,localize})=>{const item=(Object.values(transaction.branches)[0]?.stageData.origin as any)?.item;if(!item)return'';const row=(label:string,result:unknown)=>`<div class="metric-row"><span class="value">${escape(localize(label))}:</span><span class="value-result">${escape(result)}</span></div>`,parts:string[]=[];parts.push(`<div class="sdf-item-header">${item.img?`<img src="${escape(item.img)}" alt="">`:''}<strong>${escape(item.name)}</strong></div>`);if(Number(item.blast?.radius)>0)parts.push(row('SDF.Combat.BlastRadius',`${Number(item.blast.radius)} m${item.blast.dropoff?` · ${Number(item.blast.dropoff)}/m`:''}`));const active=(item.activeSelfEffects??[]).map((effect:any)=>effect?.name).filter(Boolean);if(active.length)parts.push(`<div class="metric-row"><span class="value">${escape(localize('SDF.Effects.AlreadyActive'))}:</span><span class="value-result">${escape(active.join(', '))}</span></div>`);return`<div class="sdf-combat-origin sdf-item-use"><div class="sdf-combat-group">${parts.join('')}</div></div>`})}
// No-roll item usage (drugs, toxins, gadgets): the system only posts a description card, so the
// module builds its own transaction card with pending effects; the system card stays untouched.
async function createItemUseCard(item:any){const record={kind:'ItemUseAction',title:item.name,actorUuid:item.actor?.uuid,actorName:item.actor?.name,itemName:item.name,rollMode:String(game.settings.get('core','messageMode')),modifiers:[]};let tx=createTransaction(record as any,game.user.id);tx.flowId='item-use';const extracted=await extractOrigin(['itemUse'],{testClass:'ItemUseAction',data:{},test:{item}});const targetDocuments=[...(game.user?.targets??[])].map((token:any)=>token.document??token);tx=await addSelectedTargets(tx,{targets:targetDocuments},game.user.id);for(const branch of Object.values(tx.branches)){branch.stageId='done';branch.stageData.origin=extracted}const actorUuid=item.actor?.uuid;if(actorUuid){const id=`self-${actorUuid.replace(/\./g,'-')}`;tx.branches[id]={id,kind:'self',actorUuid,name:item.actor?.name??actorUuid,stageId:'done',rolls:{},stageData:{origin:extracted},derived:{},confirmations:{}}}
// Snapshot without dynamic resolution (no live test exists); formulas render as-is on the card.
const targetedRaw=effectList(item).filter(isTargetedEffect).map((effect:any)=>effect.toObject?.()??effect),selfRaw=effectList(item).filter(isSelfEffect).map((effect:any)=>effect.toObject?.()??effect),base={itemUuid:item.uuid,itemName:item.name,source:'item'as const,unresolved:true};const entries:PendingEffectEntry[]=[];for(const branch of Object.values(tx.branches)){if(branch.kind==='target'&&targetedRaw.length)entries.push({branchId:branch.id,effects:buildPendingEffects(targetedRaw,base),count:targetedRaw.length});if(branch.kind==='self'&&selfRaw.length)entries.push({branchId:branch.id,effects:buildPendingEffects(selfRaw,base),count:selfRaw.length})}
if(!entries.length)return;tx=setPendingEffects(tx,tx.revision,game.user.id,entries);tx.complete=true;await createMessage(tx,record.rollMode)}
export function registerItemUseHook(){Hooks.on('SR5_CastItemAction',(item:any)=>{try{if(!item||item.hasRoll)return;if(!effectList(item).some(effect=>isTargetedEffect(effect)||isSelfEffect(effect)))return;void createItemUseCard(item)}catch(error){console.warn(`${MODULE_ID} | item use capture failed`,error)}})}
