import{extractors}from'../core/flows/registry';import type{FlowOrigin}from'../core/flows/spec';import{cardSections}from'./card-sections';import{isIllegalAction,matrixActionInfo}from'../core/matrix-actions';
export function matrixOriginExtractor(origin:FlowOrigin){const data=origin.data??{},marks=Number(data.marks),info=matrixActionInfo(origin.test?.item?.name);return{matrix:{marks:Number.isFinite(marks)&&marks>0?marks:undefined,action:info?{key:info.key,marks:info.marks,limit:info.limit,illegal:isIllegalAction(info),note:info.note}:undefined}}}
export function overwatchOriginExtractor(origin:FlowOrigin){const score=Number(origin.test?.actor?.getOverwatchScore?.());return{overwatch:{score:Number.isFinite(score)?score:undefined}}}
export function registerMatrixPresentation(){
 if(!extractors.has('matrixOrigin'))extractors.register('matrixOrigin',matrixOriginExtractor);
 if(!extractors.has('overwatchOrigin'))extractors.register('overwatchOrigin',overwatchOriginExtractor);
 if(!cardSections.has('matrixOrigin'))cardSections.register('matrixOrigin',({transaction,escape,localize})=>{const matrix=(Object.values(transaction.branches)[0]?.stageData.origin as any)?.matrix;if(!matrix?.marks&&!matrix?.action)return'';const row=(label:string,result:unknown)=>`<div class="metric-row"><span class="value">${escape(localize(label))}:</span><span class="value-result">${escape(result)}</span></div>`,parts:string[]=[];if(matrix.marks)parts.push(row('SDF.Matrix.PlannedMarks',matrix.marks));const info=matrix.action;if(info){const marks=info.marks==='owner'?localize('SDF.Matrix.MarksOwner'):info.marks==='special'?localize('SDF.Matrix.MarksSpecial'):info.marks;parts.push(row('SDF.Matrix.RequiredMarks',marks));parts.push(row('SDF.Matrix.Legality',localize(info.illegal?`SDF.Matrix.Illegal.${info.limit}`:'SDF.Matrix.Legal')));if(info.illegal)parts.push(`<small>${escape(localize(`SDF.Matrix.FailNote.${info.limit}`))} ${escape(localize('SDF.Matrix.OverwatchIllegal'))}</small>`);if(info.note)parts.push(`<small>${escape(localize(`SDF.Matrix.Note.${info.note}`))}</small>`)}return`<div class="sdf-combat-origin sdf-matrix-origin"><div class="sdf-combat-group"><strong><i class="fas fa-network-wired"></i> ${escape(localize('SDF.Matrix.Label'))}</strong>${parts.join('')}</div></div>`});
 if(!cardSections.has('overwatchOrigin'))cardSections.register('overwatchOrigin',({transaction,escape,localize})=>{const overwatch=(Object.values(transaction.branches)[0]?.stageData.origin as any)?.overwatch;if(!overwatch||overwatch.score===undefined)return'';return`<div class="sdf-combat-origin sdf-matrix-origin"><div class="sdf-combat-group"><strong><i class="fas fa-satellite-dish"></i> ${escape(localize('SDF.Matrix.Overwatch'))}</strong><div class="metric-row"><span class="value">${escape(localize('SDF.Matrix.OverwatchScore'))}:</span><span class="value-result">${escape(overwatch.score)}</span></div><small>${escape(localize('SDF.Matrix.OverwatchNote'))}</small></div></div>`});
}
