import{extractors}from'../core/flows/registry';import type{FlowOrigin}from'../core/flows/spec';import{cardSections}from'./card-sections';
export function matrixOriginExtractor(origin:FlowOrigin){const data=origin.data??{},marks=Number(data.marks);return{matrix:{marks:Number.isFinite(marks)&&marks>0?marks:undefined}}}
export function overwatchOriginExtractor(origin:FlowOrigin){const score=Number(origin.test?.actor?.getOverwatchScore?.());return{overwatch:{score:Number.isFinite(score)?score:undefined}}}
export function registerMatrixPresentation(){
 if(!extractors.has('matrixOrigin'))extractors.register('matrixOrigin',matrixOriginExtractor);
 if(!extractors.has('overwatchOrigin'))extractors.register('overwatchOrigin',overwatchOriginExtractor);
 if(!cardSections.has('matrixOrigin'))cardSections.register('matrixOrigin',({transaction,escape,localize})=>{const matrix=(Object.values(transaction.branches)[0]?.stageData.origin as any)?.matrix;if(!matrix?.marks)return'';return`<div class="sdf-combat-origin sdf-matrix-origin"><div class="sdf-combat-group"><strong><i class="fas fa-network-wired"></i> ${escape(localize('SDF.Matrix.Label'))}</strong><div class="metric-row"><span class="value">${escape(localize('SDF.Matrix.PlannedMarks'))}:</span><span class="value-result">${escape(matrix.marks)}</span></div></div></div>`});
 if(!cardSections.has('overwatchOrigin'))cardSections.register('overwatchOrigin',({transaction,escape,localize})=>{const overwatch=(Object.values(transaction.branches)[0]?.stageData.origin as any)?.overwatch;if(!overwatch||overwatch.score===undefined)return'';return`<div class="sdf-combat-origin sdf-matrix-origin"><div class="sdf-combat-group"><strong><i class="fas fa-satellite-dish"></i> ${escape(localize('SDF.Matrix.Overwatch'))}</strong><div class="metric-row"><span class="value">${escape(localize('SDF.Matrix.OverwatchScore'))}:</span><span class="value-result">${escape(overwatch.score)}</span></div><small>${escape(localize('SDF.Matrix.OverwatchNote'))}</small></div></div>`});
}
