import {MODULE_ID,SOCKET_PROTOCOL_VERSION,type Mutation} from '../types'; import {activeGM,canOwn,validateMutation} from './security'; import {getTransaction} from './store';
type Handler=(request:Mutation,message:any)=>Promise<void>;type Pending={resolve:(x:any)=>void;reject:(e:Error)=>void};
export const LEGACY_SOCKET_ACTIONS=new Set(['addTarget','defend','resist','damageApplied']);
export const requestId=()=>globalThis.crypto?.randomUUID?.()??`${Date.now()}-${Math.random().toString(36).slice(2)}`;
export const packetProtocol=(packet:any)=>Number(packet?.protocolVersion??1);
export const isProtocolCompatible=(packet:any)=>packetProtocol(packet)===SOCKET_PROTOCOL_VERSION||packetProtocol(packet)===1&&packet?.type==='request'&&LEGACY_SOCKET_ACTIONS.has(packet?.request?.action);
const protocolError=()=>game.i18n.localize('SDF.Error.ProtocolMismatch');
export class SocketController{handlers=new Map<string,Handler>();pending=new Map<string,Pending>();register(action:string,handler:Handler){this.handlers.set(action,handler)}start(){game.socket.on(`module.${MODULE_ID}`,(p:any)=>void this.receive(p))}async request(messageUuid:string,request:Mutation){const gm=activeGM();if(!gm)throw new Error(game.i18n.localize('SDF.Error.NoGM'));return new Promise((resolve,reject)=>{this.pending.set(request.requestId,{resolve,reject});game.socket.emit(`module.${MODULE_ID}`,{protocolVersion:SOCKET_PROTOCOL_VERSION,type:'request',to:gm.id,messageUuid,request})})}private respond(packet:any,result?:true,error?:string){game.socket.emit(`module.${MODULE_ID}`,{protocolVersion:SOCKET_PROTOCOL_VERSION,type:'response',to:packet.request.userId,requestId:packet.request.requestId,...(error?{error}:{result})})}async receive(packet:any){if(packet.to&&packet.to!==game.user.id)return;if(packet.type==='response'){const pending=this.pending.get(packet.requestId);if(!pending)return;this.pending.delete(packet.requestId);if(!isProtocolCompatible(packet))pending.reject(new Error(protocolError()));else if(packet.error)pending.reject(new Error(packet.error));else pending.resolve(packet.result);return}if(packet.type!=='request'||!game.user.isGM||activeGM()?.id!==game.user.id)return;if(!isProtocolCompatible(packet)){this.respond(packet,undefined,protocolError());return}try{if(packet.request.action==='economy'){const user=game.users.get(packet.request.userId);if(!await canOwn(user,(packet.request.payload as any)?.actorUuid))throw new Error('Actor ownership required');const handler=this.handlers.get('economy');if(!handler)throw new Error('Unknown action');await handler(packet.request,undefined);this.respond(packet,true);return}const message=await fromUuid(packet.messageUuid);const tx=await getTransaction(message);if(!tx)throw new Error('Transaction not found');const user=game.users.get(packet.request.userId);await validateMutation(tx,packet.request,user);const handler=this.handlers.get(packet.request.action);if(!handler)throw new Error('Unknown action');await handler(packet.request,message);this.respond(packet,true)}catch(error:any){this.respond(packet,undefined,error.message)}}}
export const socket=new SocketController();
