import{extractors}from'../core/flows/registry';import type{FlowOrigin}from'../core/flows/spec';import{cardSections}from'./card-sections';import{chaseRamDamage,RAM_AP,RAM_CONTROL_THRESHOLDS,ramDamage}from'../core/flows/specs/vehicle';
const stat=(value:any)=>{const v=Number(value?.value??value?.base??value);return Number.isFinite(v)?v:0};
export function vehicleOriginExtractor(origin:FlowOrigin){const actor=origin.test?.actor;if(actor?.type!=='vehicle')return{};const system=actor.system??{},stats=system.vehicle_stats??{};return{vehicle:{controlMode:String(system.controlMode??'manual'),isDrone:Boolean(system.isDrone),handling:stat(stats.handling),offRoadHandling:stat(stats.off_road_handling),speed:stat(stats.speed),offRoadSpeed:stat(stats.off_road_speed),acceleration:stat(stats.acceleration),pilot:stat(stats.pilot),sensor:stat(stats.sensor),seats:stat(stats.seats),body:stat(system.attributes?.body),armor:stat(system.armor?.rating??system.armor)}}}
export function registerVehiclePresentation(){
 if(!extractors.has('vehicleOrigin'))extractors.register('vehicleOrigin',vehicleOriginExtractor);
 if(!cardSections.has('vehicleOrigin'))cardSections.register('vehicleOrigin',({transaction,escape,localize})=>{const vehicle=(Object.values(transaction.branches)[0]?.stageData.origin as any)?.vehicle;if(!vehicle)return'';const row=(label:string,result:unknown)=>`<div class="metric-row"><span class="value">${escape(localize(label))}:</span><span class="value-result">${escape(result)}</span></div>`,parts:string[]=[];const modeKey=`SDF.Vehicle.Mode.${vehicle.controlMode}`;parts.push(`<div class="sdf-combat-group"><strong><i class="fas fa-car-side"></i> ${escape(localize('SDF.Vehicle.Label'))}</strong>${row('SDF.Vehicle.Handling',vehicle.offRoadHandling&&vehicle.offRoadHandling!==vehicle.handling?`${vehicle.handling} / ${vehicle.offRoadHandling}`:vehicle.handling)}${row('SDF.Vehicle.Speed',vehicle.offRoadSpeed&&vehicle.offRoadSpeed!==vehicle.speed?`${vehicle.speed} / ${vehicle.offRoadSpeed}`:vehicle.speed)}${row('SDF.Vehicle.Acceleration',vehicle.acceleration)}${row('SDF.Vehicle.Body',vehicle.body)}${row('SDF.Vehicle.Armor',vehicle.armor)}${row('SDF.Vehicle.Pilot',vehicle.pilot)}${row('SDF.Vehicle.Sensor',vehicle.sensor)}${row('SDF.Vehicle.ControlMode',game.i18n.has?.(modeKey)?localize(modeKey):vehicle.controlMode)}</div>`);
 const netHits=Number(Object.values(transaction.branches).find(branch=>branch.kind==='target')?.derived.netHits??0),ram=chaseRamDamage(vehicle.body,netHits);
 parts.push(`<details class="sdf-combat-group"><summary><i class="fas fa-car-burst"></i> ${escape(localize('SDF.Vehicle.RamTitle'))}</summary><p>${escape(game.i18n.format('SDF.Vehicle.RamChase',{target:ram.target,self:ram.self,ap:RAM_AP}))}</p><p>${escape(game.i18n.format('SDF.Vehicle.RamTable',{low:ramDamage(vehicle.body,10),mid:ramDamage(vehicle.body,50),high:ramDamage(vehicle.body,200),max:ramDamage(vehicle.body,201),ap:RAM_AP}))}</p><p>${escape(game.i18n.format('SDF.Vehicle.RamControl',{rammer:RAM_CONTROL_THRESHOLDS.rammer,rammed:RAM_CONTROL_THRESHOLDS.rammed}))}</p></details>`);
 parts.push(`<details class="sdf-combat-group"><summary><i class="fas fa-flag-checkered"></i> ${escape(localize('SDF.Vehicle.ChaseTitle'))}</summary><p>${escape(game.i18n.format('SDF.Vehicle.ChaseHint',{accel:vehicle.acceleration}))}</p><p>${escape(localize('SDF.Vehicle.TerrainHint'))}</p></details>`);
 return`<div class="sdf-combat-origin sdf-vehicle-origin">${parts.join('')}</div>`});
}
