import {SCHEMA_VERSION,type Branch,type FlowEvent,type RollRecord,type Transaction} from '../types';
const uid=()=>globalThis.crypto?.randomUUID?.()??`${Date.now()}-${Math.random().toString(36).slice(2)}`;
const now=()=>Date.now(); const clone=<T>(x:T):T=>structuredClone(x);
export class RevisionConflict extends Error {constructor(){super('Transaction revision conflict');this.name='RevisionConflict'}}
export function event(type:string,userId:string,payload:Record<string,unknown>={}):FlowEvent{return{id:uid(),type,at:now(),userId,payload}}
export function createTransaction(origin:Omit<RollRecord,'id'|'createdAt'>|RollRecord,authorId:string):Transaction{const roll={...origin,id:uid(),createdAt:now()};const created=now();return{schemaVersion:SCHEMA_VERSION,flowId:'combat-attack',id:uid(),revision:0,authorId,createdAt:created,updatedAt:created,origin:roll,branches:{},events:[event('transaction.created',authorId,{rollId:roll.id})],complete:false}}
export function mutate(tx:Transaction,expected:number,userId:string,fn:(draft:Transaction)=>void,eventType:string,payload:Record<string,unknown>={}):Transaction{if(tx.revision!==expected)throw new RevisionConflict();const out=clone(tx);fn(out);out.revision++;out.updatedAt=now();out.events.push(event(eventType,userId,payload));return out}
export function addTarget(tx:Transaction,expected:number,userId:string,input:{actorUuid:string;tokenUuid?:string;documentUuid?:string;name:string;id?:string}):Transaction{return mutate(tx,expected,userId,d=>{if(Object.values(d.branches).some(t=>t.kind==='target'&&t.actorUuid===input.actorUuid&&t.tokenUuid===input.tokenUuid))throw new Error('Target already exists');const id=input.id??uid();const needsDefense=Boolean(d.origin.defenseTest&&(d.origin.hits??0)>0);d.branches[id]={...input,id,kind:'target',stageId:needsDefense?'defense':'done',rolls:{},stageData:{},derived:needsDefense?{}:{netHits:0,finalDamage:0},confirmations:{}};d.complete=Object.values(d.branches).every(t=>t.stageId==='done')},'target.added',{actorUuid:input.actorUuid})}
export function setDefense(tx:Transaction,expected:number,userId:string,targetId:string,roll:RollRecord,flow?:{data?:unknown;baseDamage?:number;modifiedDamage?:number;damageType?:string}):Transaction{return mutate(tx,expected,userId,d=>{const t=d.branches[targetId];if(!t)throw new Error('Unknown target');if(t.stageId!=='defense')throw new Error('Defense already resolved');t.rolls.defense=roll;if(flow?.data!==undefined)t.stageData.defense=flow.data;t.derived.netHits=Math.max(0,(d.origin.hits??0)-(roll.hits??0));t.derived.baseDamage=flow?.baseDamage;t.derived.modifiedDamage=flow?.modifiedDamage;t.derived.damageType=flow?.damageType;const needsResistance=(t.derived.netHits as number)>0&&Boolean(d.origin.resistanceTest)&&(t.derived.modifiedDamage??0)>0;t.stageId=needsResistance?'soak':'done';if(!needsResistance)t.derived.finalDamage=t.derived.netHits===0?0:Math.max(0,Number(t.derived.modifiedDamage??t.derived.baseDamage??0));d.complete=Object.values(d.branches).every(target=>target.stageId==='done')},'target.defended',{targetId,rollId:roll.id})}
export function setResistance(tx:Transaction,expected:number,userId:string,targetId:string,roll:RollRecord,finalDamage?:number):Transaction{return mutate(tx,expected,userId,d=>{const t=d.branches[targetId];if(!t||t.stageId!=='soak')throw new Error('Target is not ready to resist');t.rolls.soak=roll;t.derived.soakHits=roll.hits??0;t.derived.finalDamage=typeof finalDamage==='number'&&Number.isFinite(finalDamage)?Math.max(0,finalDamage):Math.max(0,Number(t.derived.modifiedDamage??t.derived.baseDamage??0)-Number(t.derived.soakHits));t.stageId='done';d.complete=Object.values(d.branches).length>0&&Object.values(d.branches).every(x=>x.stageId==='done')},'target.resisted',{targetId,rollId:roll.id})}
export function setDamageApplied(tx:Transaction,expected:number,userId:string,targetId:string,applied:{value:number;type:string}):Transaction{return mutate(tx,expected,userId,d=>{const t=d.branches[targetId];if(!t)throw new Error('Unknown target');if(t.stageId!=='done')throw new Error('Damage is not final yet');if(t.confirmations.damageApplied)throw new Error('Damage already applied');t.confirmations.damageApplied={at:now(),by:userId,payload:applied}},'target.damageApplied',{targetId,value:applied.value,type:applied.type})}
export function setConfirmation(tx:Transaction,expected:number,userId:string,branchId:string,confirmationId:string,payload:unknown):Transaction{return mutate(tx,expected,userId,d=>{const branch=d.branches[branchId];if(!branch)throw new Error('Unknown branch');if(branch.confirmations[confirmationId])throw new Error('Confirmation already applied');branch.confirmations[confirmationId]={at:now(),by:userId,payload}},'confirmation.applied',{branchId,confirmationId})}
export interface PendingEffectEntry {branchId:string;effects:unknown;count:number}
export function setPendingEffects(tx:Transaction,expected:number,userId:string,entries:PendingEffectEntry[]):Transaction{return mutate(tx,expected,userId,d=>{for(const entry of entries){const branch=d.branches[entry.branchId];if(!branch)throw new Error('Unknown branch');if(branch.stageData.effects!==undefined)throw new Error('Pending effects already recorded');branch.stageData.effects=entry.effects;if(entry.count>0)branch.derived[branch.kind==='self'?'selfPendingEffects':'pendingEffects']=entry.count}},'effects.pending',{branchIds:entries.map(entry=>entry.branchId),count:entries.reduce((sum,entry)=>sum+entry.count,0)})}
export function setCalledShotAnnounced(tx:Transaction,expected:number,userId:string,value:boolean):Transaction{return mutate(tx,expected,userId,d=>{d.calledShotAnnounced=value||undefined},'calledShot.announced',{value})}
export function invalidateEvent(tx:Transaction,expected:number,userId:string,eventId:string,reason:string):Transaction{return mutate(tx,expected,userId,d=>{const e=d.events.find(x=>x.id===eventId);if(!e)throw new Error('Unknown event');if(e.invalidated)throw new Error('Event already invalidated');e.invalidated={at:now(),by:userId,reason}},'event.invalidated',{eventId,reason})}
const stageId=(stage:string)=>stage==='created'||stage==='defending'?'defense':stage==='defended'||stage==='resisting'?'soak':stage==='complete'?'done':stage;
function migrateBranch(input:any,id:string):Branch{const derived:Branch['derived']={};for(const key of ['netHits','baseDamage','modifiedDamage','soakHits','finalDamage','damageType'])if(input[key]!==undefined)derived[key]=input[key];const confirmations:Branch['confirmations']={};if(input.damageApplied)confirmations.damageApplied={at:input.damageApplied.at,by:input.damageApplied.by,payload:{value:input.damageApplied.value,type:input.damageApplied.type}};return{id:input.id??id,kind:'target',actorUuid:input.actorUuid,tokenUuid:input.tokenUuid,documentUuid:input.documentUuid,name:input.name,stageId:stageId(input.stage),rolls:{...(input.defense?{defense:input.defense}:{}),...(input.resistance?{soak:input.resistance}:{})},stageData:input.defenseData===undefined?{}:{defense:input.defenseData},derived,confirmations}}
export function migrate(input:any):Transaction{if(input?.schemaVersion===SCHEMA_VERSION)return input;if(input?.schemaVersion===1){const{targets,...rest}=input;return{...rest,schemaVersion:SCHEMA_VERSION,flowId:'combat-attack',branches:Object.fromEntries(Object.entries(targets??{}).map(([id,target])=>[id,migrateBranch(target,id)]))}}if(!input?.schemaVersion)throw new Error('Unsupported transaction schema');throw new Error(`No migration from schema ${input.schemaVersion}`)}
